'use strict';
/* WB 워드브레인 — 시드 단어 데이터 (초5~중2, 비문학·사고 도구 어휘 중심)
   type: hanja(한자어) | native(고유어) | english(영어)
   공통: id, word, meaning, example
   hanja: hanja, parts[{ch,hun,eum}], literal(조립 뜻)
   english: pron, cue(키워드 연상), scene(연상 장면), root{stem,sense,family[]}(선택)
   native: scene(이미지 연상 장면), syn[](유의어) */
var WB_WORDS = [
  /* ── 한자어 15 ─────────────────────────────── */
  { id: 'h-gwancheuk', type: 'hanja', word: '관측', hanja: '觀測',
    parts: [{ ch: '觀', hun: '볼', eum: '관' }, { ch: '測', hun: '잴', eum: '측' }],
    literal: '보고 잰다',
    meaning: '눈이나 기계로 자연 현상을 자세히 살펴 재는 것',
    example: '천문대에서 별의 움직임을 관측했다.' },
  { id: 'h-gwanjeom', type: 'hanja', word: '관점', hanja: '觀點',
    parts: [{ ch: '觀', hun: '볼', eum: '관' }, { ch: '點', hun: '점', eum: '점' }],
    literal: '바라보는 지점',
    meaning: '사물이나 사건을 바라보는 자기만의 자리, 시각',
    example: '같은 사건도 관점에 따라 다르게 보인다.' },
  { id: 'h-gaekgwan', type: 'hanja', word: '객관', hanja: '客觀',
    parts: [{ ch: '客', hun: '손님', eum: '객' }, { ch: '觀', hun: '볼', eum: '관' }],
    literal: '손님처럼 본다',
    meaning: '내 감정에서 떨어져 제3자의 눈으로 보는 것',
    example: '심판은 객관적인 눈으로 판정해야 한다.' },
  { id: 'h-jugwan', type: 'hanja', word: '주관', hanja: '主觀',
    parts: [{ ch: '主', hun: '주인', eum: '주' }, { ch: '觀', hun: '볼', eum: '관' }],
    literal: '주인으로서 본다',
    meaning: '자기 생각과 느낌을 중심으로 보는 것',
    example: '일기에는 나의 주관이 그대로 담긴다.' },
  { id: 'h-churon', type: 'hanja', word: '추론', hanja: '推論',
    parts: [{ ch: '推', hun: '밀', eum: '추' }, { ch: '論', hun: '논할', eum: '론' }],
    literal: '밀고 나가 논한다',
    meaning: '아는 사실을 바탕으로 모르는 것을 미루어 생각함',
    example: '발자국의 크기를 보고 범인의 키를 추론했다.' },
  { id: 'h-nonjeung', type: 'hanja', word: '논증', hanja: '論證',
    parts: [{ ch: '論', hun: '논할', eum: '론' }, { ch: '證', hun: '증거', eum: '증' }],
    literal: '증거를 대어 논한다',
    meaning: '이유와 증거를 들어 주장이 옳음을 밝히는 것',
    example: '글쓴이는 세 가지 근거로 주장을 논증했다.' },
  { id: 'h-banron', type: 'hanja', word: '반론', hanja: '反論',
    parts: [{ ch: '反', hun: '돌이킬', eum: '반' }, { ch: '論', hun: '논할', eum: '론' }],
    literal: '되돌려 논한다',
    meaning: '상대의 주장에 맞서 되받아치는 주장',
    example: '토론에서 상대의 반론에 침착하게 답했다.' },
  { id: 'h-mosun', type: 'hanja', word: '모순', hanja: '矛盾',
    parts: [{ ch: '矛', hun: '창', eum: '모' }, { ch: '盾', hun: '방패', eum: '순' }],
    literal: '무엇이든 뚫는 창 + 무엇이든 막는 방패',
    meaning: '말이나 행동의 앞뒤가 서로 맞지 않음',
    example: '일찍 자라면서 밤새 공부하라는 말은 모순이다.' },
  { id: 'h-tadang', type: 'hanja', word: '타당', hanja: '妥當',
    parts: [{ ch: '妥', hun: '온당할', eum: '타' }, { ch: '當', hun: '마땅', eum: '당' }],
    literal: '온당하고 마땅하다',
    meaning: '이치에 맞아 옳다고 할 만함',
    example: '그 주장은 근거가 충분해서 타당하다.' },
  { id: 'h-jeonje', type: 'hanja', word: '전제', hanja: '前提',
    parts: [{ ch: '前', hun: '앞', eum: '전' }, { ch: '提', hun: '끌', eum: '제' }],
    literal: '앞에 끌어다 놓음',
    meaning: '어떤 주장이 성립하도록 미리 깔아 두는 조건',
    example: '약속은 지킨다는 전제 위에서 이루어진다.' },
  { id: 'h-hamchuk', type: 'hanja', word: '함축', hanja: '含蓄',
    parts: [{ ch: '含', hun: '머금을', eum: '함' }, { ch: '蓄', hun: '쌓을', eum: '축' }],
    literal: '머금고 쌓아 둔다',
    meaning: '겉으로 다 말하지 않고 속에 담아 둔 뜻',
    example: '이 시의 마지막 행은 깊은 슬픔을 함축한다.' },
  { id: 'h-seongchal', type: 'hanja', word: '성찰', hanja: '省察',
    parts: [{ ch: '省', hun: '살필', eum: '성' }, { ch: '察', hun: '살필', eum: '찰' }],
    literal: '살피고 또 살핀다',
    meaning: '자기 마음과 행동을 돌이켜 깊이 살펴봄',
    example: '하루를 마치며 나의 말과 행동을 성찰했다.' },
  { id: 'h-jeolchung', type: 'hanja', word: '절충', hanja: '折衷',
    parts: [{ ch: '折', hun: '꺾을', eum: '절' }, { ch: '衷', hun: '속마음', eum: '충' }],
    literal: '양쪽을 꺾어 가운데 마음을 취한다',
    meaning: '서로 다른 의견에서 좋은 점을 골라 알맞게 맞춤',
    example: '두 팀의 계획을 절충해 새로운 안을 만들었다.' },
  { id: 'h-chegye', type: 'hanja', word: '체계', hanja: '體系',
    parts: [{ ch: '體', hun: '몸', eum: '체' }, { ch: '系', hun: '이어맬', eum: '계' }],
    literal: '한 몸처럼 이어 묶음',
    meaning: '낱낱의 것이 짜임새 있게 이어진 전체 틀',
    example: '도서관의 책은 분류 체계에 따라 꽂혀 있다.' },
  { id: 'h-mumo', type: 'hanja', word: '무모', hanja: '無謀',
    parts: [{ ch: '無', hun: '없을', eum: '무' }, { ch: '謀', hun: '꾀할', eum: '모' }],
    literal: '꾀함(계획)이 없다',
    meaning: '앞뒤 계획 없이 마구 덤빔',
    example: '준비 없이 겨울 산에 오르는 것은 무모하다.' },

  /* ── 영어 15 ──────────────────────────────── */
  { id: 'e-observe', type: 'english', word: 'observe', pron: '옵저브',
    cue: '"옵! 저(것) 봐!"',
    scene: '"옵! 저 봐!" 소리치며 돋보기로 자세히 들여다보는 장면',
    meaning: '관찰하다, 자세히 살펴보다',
    example: 'Scientists observe the stars every night.' },
  { id: 'e-predict', type: 'english', word: 'predict', pron: '프리딕트',
    cue: '미리(pre) 말하다(dict)',
    scene: '일기예보관이 내일 날씨를 미리 말해 주는 장면',
    root: { stem: 'dict', sense: '말하다', family: ['dictionary', 'dictation'] },
    meaning: '예측하다',
    example: 'Can you predict tomorrow’s weather?' },
  { id: 'e-evidence', type: 'english', word: 'evidence', pron: '에비던스',
    cue: 'vid = 보다 → 눈에 보이게 드러난 것',
    scene: '탐정이 돋보기로 진흙 위 발자국을 가리키는 장면',
    root: { stem: 'vid', sense: '보다', family: ['video', 'visible'] },
    meaning: '증거',
    example: 'The detective found new evidence.' },
  { id: 'e-conclude', type: 'english', word: 'conclude', pron: '컨클루드',
    cue: '함께(con) 문을 닫다(clude) → 이야기를 닫다',
    scene: '"오늘 회의는 여기까지!" 하며 문을 닫는 장면',
    root: { stem: 'clude', sense: '닫다', family: ['include', 'exclude'] },
    meaning: '결론을 내리다, 끝맺다',
    example: 'The report concludes that exercise helps memory.' },
  { id: 'e-estimate', type: 'english', word: 'estimate', pron: '에스티메이트',
    cue: 'S.T. 메이트(친구)가 값을 척 보고 어림잡는다',
    scene: '친구가 나무를 척 보더니 "한 10미터?" 하는 장면',
    meaning: '어림잡다, 추정하다',
    example: 'Can you estimate the height of that tree?' },
  { id: 'e-compare', type: 'english', word: 'compare', pron: '컴페어',
    cue: '짝(pair)을 함께(com) 놓고 견주다',
    scene: '저울 양쪽에 사과와 배를 올려 견주는 장면',
    root: { stem: 'par', sense: '같은, 짝', family: ['pair', 'part'] },
    meaning: '비교하다',
    example: 'Compare the two pictures and find the differences.' },
  { id: 'e-examine', type: 'english', word: 'examine', pron: '이그재민',
    cue: '"이그, 재 민(이)!" — 뭐든 자로 재 보는 민이',
    scene: '의사 선생님이 청진기로 구석구석 살피는 장면',
    meaning: '자세히 조사하다, 진찰하다',
    example: 'The doctor examined the patient carefully.' },
  { id: 'e-insist', type: 'english', word: 'insist', pron: '인시스트',
    cue: '자기 주장 안(in)에 버티고 서다(sist)',
    scene: '팔짱을 끼고 "무조건 이거야!" 버티는 장면',
    root: { stem: 'sist', sense: '서다', family: ['assist', 'consist'] },
    meaning: '고집하다, 강하게 주장하다',
    example: 'She insisted that she was right.' },
  { id: 'e-persuade', type: 'english', word: 'persuade', pron: '퍼수에이드',
    cue: '"퍼 줘!" 하며 마음을 얻는다',
    scene: '"아이스크림 퍼 줄게" 하며 동생 마음을 돌리는 장면',
    meaning: '설득하다',
    example: 'He persuaded his parents to buy a puppy.' },
  { id: 'e-achieve', type: 'english', word: 'achieve', pron: '어치브',
    cue: '"아, 치익—" 결승선을 끊고 브이(V)!',
    scene: '결승선 테이프를 끊으며 브이를 그리는 장면',
    meaning: '이루다, 달성하다',
    example: 'She achieved her goal of reading 100 books.' },
  { id: 'e-purpose', type: 'english', word: 'purpose', pron: '퍼포스',
    cue: '무대 위 모든 포즈(pose)에는 목적이 있다',
    scene: '안무가가 "이 포즈의 목적은?" 하고 묻는 장면',
    meaning: '목적',
    example: 'What is the purpose of this experiment?' },
  { id: 'e-method', type: 'english', word: 'method', pron: '메소드',
    cue: '레시피대로 차근차근 — 요리엔 방법이 있다',
    scene: '레시피 순서를 손가락으로 짚으며 요리하는 장면',
    meaning: '방법, 방식',
    example: 'This is a new method for learning words.' },
  { id: 'e-region', type: 'english', word: 'region', pron: '리전',
    cue: '리(里)장님이 다스리는 우리 지역',
    scene: '이장님이 마을 지도를 펼쳐 "여기가 우리 리!" 하는 장면',
    meaning: '지역, 지방',
    example: 'This region is famous for its apples.' },
  { id: 'e-curious', type: 'english', word: 'curious', pron: '큐리어스',
    cue: '퀴리 부인은 호기심 대장',
    scene: '퀴리 부인이 반짝이는 눈으로 실험을 들여다보는 장면',
    meaning: '호기심 많은, 궁금한',
    example: 'The curious cat opened the box.' },
  { id: 'e-effort', type: 'english', word: 'effort', pron: '에퍼트',
    cue: '요새(fort)를 쌓으려면 돌 하나하나의 노력',
    scene: '돌을 하나씩 쌓아 튼튼한 요새를 만드는 장면',
    meaning: '노력, 수고',
    example: 'Success needs time and effort.' },

  /* ── 고유어 15 ────────────────────────────── */
  { id: 'n-ganeum', type: 'native', word: '가늠하다',
    scene: '활을 쏘기 전, 한쪽 눈을 감고 과녁까지의 거리를 눈으로 재는 장면',
    syn: ['짐작하다', '어림하다'],
    meaning: '겉으로 보고 형편이나 정도를 대강 짐작하다',
    example: '하늘빛을 보고 비가 올지 가늠해 보았다.' },
  { id: 'n-hearida', type: 'native', word: '헤아리다',
    scene: '밤하늘의 별을 하나, 둘 세다가 친구의 마음까지 짚어 보는 장면',
    syn: ['살피다', '짐작하다'],
    meaning: '수를 세다, 남의 마음이나 형편을 짚어 생각하다',
    example: '엄마는 말하지 않아도 내 마음을 헤아려 주셨다.' },
  { id: 'n-doesaegida', type: 'native', word: '되새기다',
    scene: '소가 삼킨 풀을 다시 꺼내 씹듯, 들은 말을 다시 꺼내 곱씹는 장면',
    syn: ['곱씹다', '반추하다'],
    meaning: '지난 일이나 말을 다시 떠올려 곰곰이 생각하다',
    example: '선생님의 말씀을 잠들기 전에 되새겼다.' },
  { id: 'n-aureuda', type: 'native', word: '아우르다',
    scene: '두 팔을 크게 벌려 흩어진 친구들을 한 품에 모으는 장면',
    syn: ['모으다', '포괄하다'],
    meaning: '여럿을 한데 모아 어울리게 하다',
    example: '반장은 반 전체를 아우르는 리더였다.' },
  { id: 'n-mureupsseuda', type: 'native', word: '무릅쓰다',
    scene: '쏟아지는 비를 머리부터 뒤집어쓰고도 앞으로 걸어가는 장면',
    syn: ['감수하다', '견디다'],
    meaning: '어려움을 알면서도 그대로 견디며 해내다',
    example: '위험을 무릅쓰고 물에 빠진 강아지를 구했다.' },
  { id: 'n-galmuri', type: 'native', word: '갈무리',
    scene: '가을에 거둔 곡식을 광에 차곡차곡 쟁여 넣는 장면',
    syn: ['정리', '마무리'],
    meaning: '물건을 잘 정리해 간수함, 일을 잘 마무리함',
    example: '오늘 배운 내용을 공책에 갈무리했다.' },
  { id: 'n-gomgomi', type: 'native', word: '곰곰이',
    scene: '곰이 굴 속에서 팔짱을 끼고 오래오래 생각하는 장면',
    syn: ['깊이', '차분히'],
    meaning: '여러모로 깊이 생각하는 모양',
    example: '곰곰이 생각해 보니 내 잘못도 있었다.' },
  { id: 'n-seoseumda', type: 'native', word: '서슴다',
    scene: '문고리를 잡고 들어갈까 말까 멈칫거리는 장면',
    syn: ['머뭇거리다', '주저하다'],
    meaning: '결단을 내리지 못하고 머뭇거리다',
    example: '그는 서슴지 않고 번쩍 손을 들었다.' },
  { id: 'n-eorimjapda', type: 'native', word: '어림잡다',
    scene: '쌀가마니를 들어 보지도 않고 눈대중으로 "한 20킬로?" 하는 장면',
    syn: ['가늠하다', '어림하다'],
    meaning: '대강 짐작으로 헤아리다',
    example: '관중 수를 어림잡아 천 명으로 보았다.' },
  { id: 'n-dadogida', type: 'native', word: '다독이다',
    scene: '우는 동생의 등을 토닥토닥 두드려 주는 장면',
    syn: ['달래다', '위로하다'],
    meaning: '가볍게 두드리며 달래고 감싸다',
    example: '실수한 친구를 다독여 주었다.' },
  { id: 'n-samuchida', type: 'native', word: '사무치다',
    scene: '겨울바람이 뼛속까지 파고들듯, 그리움이 마음 깊이 파고드는 장면',
    syn: ['저미다', '깊이 스미다'],
    meaning: '깊이 스며들어 마음속까지 미치다',
    example: '고향 생각이 뼈에 사무쳤다.' },
  { id: 'n-eokcheok', type: 'native', word: '억척스럽다',
    scene: '새벽 시장에서 무거운 리어카를 끌고도 씩씩한 할머니의 손',
    syn: ['악착같다', '끈질기다'],
    meaning: '어려움에도 굽히지 않고 몹시 모질고 끈덕지다',
    example: '어머니는 억척스럽게 우리 남매를 키우셨다.' },
  { id: 'n-onggolchada', type: 'native', word: '옹골차다',
    scene: '알이 빈틈없이 꽉 들어찬 옥수수',
    syn: ['야무지다', '알차다'],
    meaning: '속이 꽉 차서 실속이 있다',
    example: '몸집은 작아도 옹골찬 선수다.' },
  { id: 'n-galpi', type: 'native', word: '갈피',
    scene: '두꺼운 책 사이에 끼운 책갈피 — 지금 어디쯤인지 알려 준다',
    syn: ['두서', '가닥'],
    meaning: '일이나 마음의 갈래와 방향',
    example: '갑작스러운 소식에 갈피를 잡지 못했다.' },
  { id: 'n-nwiuchida', type: 'native', word: '뉘우치다',
    scene: '일기장 앞에서 고개를 숙이고 "내가 잘못했구나" 하는 장면',
    syn: ['반성하다', '후회하다'],
    meaning: '잘못을 깨닫고 스스로 꾸짖다',
    example: '거짓말한 것을 깊이 뉘우쳤다.' }
];

if (typeof module !== 'undefined' && module.exports) module.exports = { WB_WORDS };
