'use strict';
/* WB 워드브레인 — 시드 단어 데이터 (초5~중2, 비문학·사고 도구 어휘 중심)
   type: hanja(한자어) | native(고유어) | english(영어)
   공통: id, word, meaning, example
   hanja: hanja, parts[{ch,hun,eum}], literal(조립 뜻)
   english: pron, cue(키워드 연상), scene(연상 장면), root{stem,sense,family[]}(선택)
   native: scene(이미지 연상 장면), syn[](유의어) */
var WB_WORDS = [
  /* ── 한자어 15 ─────────────────────────────── */
  { id: 'h-gwancheuk', type: 'hanja', word: '관측', hanja: '觀測',
    parts: [{ ch: '觀', hun: '볼', eum: '관' }, { ch: '測', hun: '잴', eum: '측' }],
    literal: '보고 잰다',
    meaning: '눈이나 기계로 자연 현상을 자세히 살펴 재는 것',
    example: '천문대에서 별의 움직임을 관측했다.' },
  { id: 'h-gwanjeom', type: 'hanja', word: '관점', hanja: '觀點',
    parts: [{ ch: '觀', hun: '볼', eum: '관' }, { ch: '點', hun: '점', eum: '점' }],
    literal: '바라보는 지점',
    meaning: '사물이나 사건을 바라보는 자기만의 자리, 시각',
    example: '같은 사건도 관점에 따라 다르게 보인다.' },
  { id: 'h-gaekgwan', type: 'hanja', word: '객관', hanja: '客觀',
    parts: [{ ch: '客', hun: '손님', eum: '객' }, { ch: '觀', hun: '볼', eum: '관' }],
    literal: '손님처럼 본다',
    meaning: '내 감정에서 떨어져 제3자의 눈으로 보는 것',
    example: '심판은 객관적인 눈으로 판정해야 한다.' },
  { id: 'h-jugwan', type: 'hanja', word: '주관', hanja: '主觀',
    parts: [{ ch: '主', hun: '주인', eum: '주' }, { ch: '觀', hun: '볼', eum: '관' }],
    literal: '주인으로서 본다',
    meaning: '자기 생각과 느낌을 중심으로 보는 것',
    example: '일기에는 나의 주관이 그대로 담긴다.' },
  { id: 'h-churon', type: 'hanja', word: '추론', hanja: '推論',
    parts: [{ ch: '推', hun: '밀', eum: '추' }, { ch: '論', hun: '논할', eum: '론' }],
    literal: '밀고 나가 논한다',
    meaning: '아는 사실을 바탕으로 모르는 것을 미루어 생각함',
    example: '발자국의 크기를 보고 범인의 키를 추론했다.' },
  { id: 'h-nonjeung', type: 'hanja', word: '논증', hanja: '論證',
    parts: [{ ch: '論', hun: '논할', eum: '론' }, { ch: '證', hun: '증거', eum: '증' }],
    literal: '증거를 대어 논한다',
    meaning: '이유와 증거를 들어 주장이 옳음을 밝히는 것',
    example: '글쓴이는 세 가지 근거로 주장을 논증했다.' },
  { id: 'h-banron', type: 'hanja', word: '반론', hanja: '反論',
    parts: [{ ch: '反', hun: '돌이킬', eum: '반' }, { ch: '論', hun: '논할', eum: '론' }],
    literal: '되돌려 논한다',
    meaning: '상대의 주장에 맞서 되받아치는 주장',
    example: '토론에서 상대의 반론에 침착하게 답했다.' },
  { id: 'h-mosun', type: 'hanja', word: '모순', hanja: '矛盾',
    parts: [{ ch: '矛', hun: '창', eum: '모' }, { ch: '盾', hun: '방패', eum: '순' }],
    literal: '무엇이든 뚫는 창 + 무엇이든 막는 방패',
    meaning: '말이나 행동의 앞뒤가 서로 맞지 않음',
    example: '일찍 자라면서 밤새 공부하라는 말은 모순이다.' },
  { id: 'h-tadang', type: 'hanja', word: '타당', hanja: '妥當',
    parts: [{ ch: '妥', hun: '온당할', eum: '타' }, { ch: '當', hun: '마땅', eum: '당' }],
    literal: '온당하고 마땅하다',
    meaning: '이치에 맞아 옳다고 할 만함',
    example: '그 주장은 근거가 충분해서 타당하다.' },
  { id: 'h-jeonje', type: 'hanja', word: '전제', hanja: '前提',
    parts: [{ ch: '前', hun: '앞', eum: '전' }, { ch: '提', hun: '끌', eum: '제' }],
    literal: '앞에 끌어다 놓음',
    meaning: '어떤 주장이 성립하도록 미리 깔아 두는 조건',
    example: '약속은 지킨다는 전제 위에서 이루어진다.' },
  { id: 'h-hamchuk', type: 'hanja', word: '함축', hanja: '含蓄',
    parts: [{ ch: '含', hun: '머금을', eum: '함' }, { ch: '蓄', hun: '쌓을', eum: '축' }],
    literal: '머금고 쌓아 둔다',
    meaning: '겉으로 다 말하지 않고 속에 담아 둔 뜻',
    example: '이 시의 마지막 행은 깊은 슬픔을 함축한다.' },
  { id: 'h-seongchal', type: 'hanja', word: '성찰', hanja: '省察',
    parts: [{ ch: '省', hun: '살필', eum: '성' }, { ch: '察', hun: '살필', eum: '찰' }],
    literal: '살피고 또 살핀다',
    meaning: '자기 마음과 행동을 돌이켜 깊이 살펴봄',
    example: '하루를 마치며 나의 말과 행동을 성찰했다.' },
  { id: 'h-jeolchung', type: 'hanja', word: '절충', hanja: '折衷',
    parts: [{ ch: '折', hun: '꺾을', eum: '절' }, { ch: '衷', hun: '속마음', eum: '충' }],
    literal: '양쪽을 꺾어 가운데 마음을 취한다',
    meaning: '서로 다른 의견에서 좋은 점을 골라 알맞게 맞춤',
    example: '두 팀의 계획을 절충해 새로운 안을 만들었다.' },
  { id: 'h-chegye', type: 'hanja', word: '체계', hanja: '體系',
    parts: [{ ch: '體', hun: '몸', eum: '체' }, { ch: '系', hun: '이어맬', eum: '계' }],
    literal: '한 몸처럼 이어 묶음',
    meaning: '낱낱의 것이 짜임새 있게 이어진 전체 틀',
    example: '도서관의 책은 분류 체계에 따라 꽂혀 있다.' },
  { id: 'h-mumo', type: 'hanja', word: '무모', hanja: '無謀',
    parts: [{ ch: '無', hun: '없을', eum: '무' }, { ch: '謀', hun: '꾀할', eum: '모' }],
    literal: '꾀함(계획)이 없다',
    meaning: '앞뒤 계획 없이 마구 덤빔',
    example: '준비 없이 겨울 산에 오르는 것은 무모하다.' },

  /* ── 영어 15 ──────────────────────────────── */
  { id: 'e-observe', type: 'english', word: 'observe', pron: '옵저브',
    cue: '"옵! 저(것) 봐!"',
    scene: '"옵! 저 봐!" 소리치며 돋보기로 자세히 들여다보는 장면',
    meaning: '관찰하다, 자세히 살펴보다',
    example: 'Scientists observe the stars every night.' },
  { id: 'e-predict', type: 'english', word: 'predict', pron: '프리딕트',
    cue: '미리(pre) 말하다(dict)',
    scene: '일기예보관이 내일 날씨를 미리 말해 주는 장면',
    root: { stem: 'dict', sense: '말하다', family: ['dictionary', 'dictation'] },
    meaning: '예측하다',
    example: 'Can you predict tomorrow’s weather?' },
  { id: 'e-evidence', type: 'english', word: 'evidence', pron: '에비던스',
    cue: 'vid = 보다 → 눈에 보이게 드러난 것',
    scene: '탐정이 돋보기로 진흙 위 발자국을 가리키는 장면',
    root: { stem: 'vid', sense: '보다', family: ['video', 'visible'] },
    meaning: '증거',
    example: 'The detective found new evidence.' },
  { id: 'e-conclude', type: 'english', word: 'conclude', pron: '컨클루드',
    cue: '함께(con) 문을 닫다(clude) → 이야기를 닫다',
    scene: '"오늘 회의는 여기까지!" 하며 문을 닫는 장면',
    root: { stem: 'clude', sense: '닫다', family: ['include', 'exclude'] },
    meaning: '결론을 내리다, 끝맺다',
    example: 'The report concludes that exercise helps memory.' },
  { id: 'e-estimate', type: 'english', word: 'estimate', pron: '에스티메이트',
    cue: 'S.T. 메이트(친구)가 값을 척 보고 어림잡는다',
    scene: '친구가 나무를 척 보더니 "한 10미터?" 하는 장면',
    meaning: '어림잡다, 추정하다',
    example: 'Can you estimate the height of that tree?' },
  { id: 'e-compare', type: 'english', word: 'compare', pron: '컴페어',
    cue: '짝(pair)을 함께(com) 놓고 견주다',
    scene: '저울 양쪽에 사과와 배를 올려 견주는 장면',
    root: { stem: 'par', sense: '같은, 짝', family: ['pair', 'part'] },
    meaning: '비교하다',
    example: 'Compare the two pictures and find the differences.' },
  { id: 'e-examine', type: 'english', word: 'examine', pron: '이그재민',
    cue: '"이그, 재 민(이)!" — 뭐든 자로 재 보는 민이',
    scene: '의사 선생님이 청진기로 구석구석 살피는 장면',
    meaning: '자세히 조사하다, 진찰하다',
    example: 'The doctor examined the patient carefully.' },
  { id: 'e-insist', type: 'english', word: 'insist', pron: '인시스트',
    cue: '자기 주장 안(in)에 버티고 서다(sist)',
    scene: '팔짱을 끼고 "무조건 이거야!" 버티는 장면',
    root: { stem: 'sist', sense: '서다', family: ['assist', 'consist'] },
    meaning: '고집하다, 강하게 주장하다',
    example: 'She insisted that she was right.' },
  { id: 'e-persuade', type: 'english', word: 'persuade', pron: '퍼수에이드',
    cue: '"퍼 줘!" 하며 마음을 얻는다',
    scene: '"아이스크림 퍼 줄게" 하며 동생 마음을 돌리는 장면',
    meaning: '설득하다',
    example: 'He persuaded his parents to buy a puppy.' },
  { id: 'e-achieve', type: 'english', word: 'achieve', pron: '어치브',
    cue: '"아, 치익—" 결승선을 끊고 브이(V)!',
    scene: '결승선 테이프를 끊으며 브이를 그리는 장면',
    meaning: '이루다, 달성하다',
    example: 'She achieved her goal of reading 100 books.' },
  { id: 'e-purpose', type: 'english', word: 'purpose', pron: '퍼포스',
    cue: '무대 위 모든 포즈(pose)에는 목적이 있다',
    scene: '안무가가 "이 포즈의 목적은?" 하고 묻는 장면',
    meaning: '목적',
    example: 'What is the purpose of this experiment?' },
  { id: 'e-method', type: 'english', word: 'method', pron: '메소드',
    cue: '레시피대로 차근차근 — 요리엔 방법이 있다',
    scene: '레시피 순서를 손가락으로 짚으며 요리하는 장면',
    meaning: '방법, 방식',
    example: 'This is a new method for learning words.' },
  { id: 'e-region', type: 'english', word: 'region', pron: '리전',
    cue: '리(里)장님이 다스리는 우리 지역',
    scene: '이장님이 마을 지도를 펼쳐 "여기가 우리 리!" 하는 장면',
    meaning: '지역, 지방',
    example: 'This region is famous for its apples.' },
  { id: 'e-curious', type: 'english', word: 'curious', pron: '큐리어스',
    cue: '퀴리 부인은 호기심 대장',
    scene: '퀴리 부인이 반짝이는 눈으로 실험을 들여다보는 장면',
    meaning: '호기심 많은, 궁금한',
    example: 'The curious cat opened the box.' },
  { id: 'e-effort', type: 'english', word: 'effort', pron: '에퍼트',
    cue: '요새(fort)를 쌓으려면 돌 하나하나의 노력',
    scene: '돌을 하나씩 쌓아 튼튼한 요새를 만드는 장면',
    meaning: '노력, 수고',
    example: 'Success needs time and effort.' },

  /* ── 고유어 15 ────────────────────────────── */
  { id: 'n-ganeum', type: 'native', word: '가늠하다',
    scene: '활을 쏘기 전, 한쪽 눈을 감고 과녁까지의 거리를 눈으로 재는 장면',
    syn: ['짐작하다', '어림하다'],
    meaning: '겉으로 보고 형편이나 정도를 대강 짐작하다',
    example: '하늘빛을 보고 비가 올지 가늠해 보았다.' },
  { id: 'n-hearida', type: 'native', word: '헤아리다',
    scene: '밤하늘의 별을 하나, 둘 세다가 친구의 마음까지 짚어 보는 장면',
    syn: ['살피다', '짐작하다'],
    meaning: '수를 세다, 남의 마음이나 형편을 짚어 생각하다',
    example: '엄마는 말하지 않아도 내 마음을 헤아려 주셨다.' },
  { id: 'n-doesaegida', type: 'native', word: '되새기다',
    scene: '소가 삼킨 풀을 다시 꺼내 씹듯, 들은 말을 다시 꺼내 곱씹는 장면',
    syn: ['곱씹다', '반추하다'],
    meaning: '지난 일이나 말을 다시 떠올려 곰곰이 생각하다',
    example: '선생님의 말씀을 잠들기 전에 되새겼다.' },
  { id: 'n-aureuda', type: 'native', word: '아우르다',
    scene: '두 팔을 크게 벌려 흩어진 친구들을 한 품에 모으는 장면',
    syn: ['모으다', '포괄하다'],
    meaning: '여럿을 한데 모아 어울리게 하다',
    example: '반장은 반 전체를 아우르는 리더였다.' },
  { id: 'n-mureupsseuda', type: 'native', word: '무릅쓰다',
    scene: '쏟아지는 비를 머리부터 뒤집어쓰고도 앞으로 걸어가는 장면',
    syn: ['감수하다', '견디다'],
    meaning: '어려움을 알면서도 그대로 견디며 해내다',
    example: '위험을 무릅쓰고 물에 빠진 강아지를 구했다.' },
  { id: 'n-galmuri', type: 'native', word: '갈무리',
    scene: '가을에 거둔 곡식을 광에 차곡차곡 쟁여 넣는 장면',
    syn: ['정리', '마무리'],
    meaning: '물건을 잘 정리해 간수함, 일을 잘 마무리함',
    example: '오늘 배운 내용을 공책에 갈무리했다.' },
  { id: 'n-gomgomi', type: 'native', word: '곰곰이',
    scene: '곰이 굴 속에서 팔짱을 끼고 오래오래 생각하는 장면',
    syn: ['깊이', '차분히'],
    meaning: '여러모로 깊이 생각하는 모양',
    example: '곰곰이 생각해 보니 내 잘못도 있었다.' },
  { id: 'n-seoseumda', type: 'native', word: '서슴다',
    scene: '문고리를 잡고 들어갈까 말까 멈칫거리는 장면',
    syn: ['머뭇거리다', '주저하다'],
    meaning: '결단을 내리지 못하고 머뭇거리다',
    example: '그는 서슴지 않고 번쩍 손을 들었다.' },
  { id: 'n-eorimjapda', type: 'native', word: '어림잡다',
    scene: '쌀가마니를 들어 보지도 않고 눈대중으로 "한 20킬로?" 하는 장면',
    syn: ['가늠하다', '어림하다'],
    meaning: '대강 짐작으로 헤아리다',
    example: '관중 수를 어림잡아 천 명으로 보았다.' },
  { id: 'n-dadogida', type: 'native', word: '다독이다',
    scene: '우는 동생의 등을 토닥토닥 두드려 주는 장면',
    syn: ['달래다', '위로하다'],
    meaning: '가볍게 두드리며 달래고 감싸다',
    example: '실수한 친구를 다독여 주었다.' },
  { id: 'n-samuchida', type: 'native', word: '사무치다',
    scene: '겨울바람이 뼛속까지 파고들듯, 그리움이 마음 깊이 파고드는 장면',
    syn: ['저미다', '깊이 스미다'],
    meaning: '깊이 스며들어 마음속까지 미치다',
    example: '고향 생각이 뼈에 사무쳤다.' },
  { id: 'n-eokcheok', type: 'native', word: '억척스럽다',
    scene: '새벽 시장에서 무거운 리어카를 끌고도 씩씩한 할머니의 손',
    syn: ['악착같다', '끈질기다'],
    meaning: '어려움에도 굽히지 않고 몹시 모질고 끈덕지다',
    example: '어머니는 억척스럽게 우리 남매를 키우셨다.' },
  { id: 'n-onggolchada', type: 'native', word: '옹골차다',
    scene: '알이 빈틈없이 꽉 들어찬 옥수수',
    syn: ['야무지다', '알차다'],
    meaning: '속이 꽉 차서 실속이 있다',
    example: '몸집은 작아도 옹골찬 선수다.' },
  { id: 'n-galpi', type: 'native', word: '갈피',
    scene: '두꺼운 책 사이에 끼운 책갈피 — 지금 어디쯤인지 알려 준다',
    syn: ['두서', '가닥'],
    meaning: '일이나 마음의 갈래와 방향',
    example: '갑작스러운 소식에 갈피를 잡지 못했다.' },
  { id: 'n-nwiuchida', type: 'native', word: '뉘우치다',
    scene: '일기장 앞에서 고개를 숙이고 "내가 잘못했구나" 하는 장면',
    syn: ['반성하다', '후회하다'],
    meaning: '잘못을 깨닫고 스스로 꾸짖다',
    example: '거짓말한 것을 깊이 뉘우쳤다.' },

  /* ── 한자어 추가 30 (비문학·학업 어휘) ────── */
  { id: 'h-gwanchal', type: 'hanja', word: '관찰', hanja: '觀察',
    parts: [{ ch: '觀', hun: '볼', eum: '관' }, { ch: '察', hun: '살필', eum: '찰' }],
    literal: '보고 살핀다',
    meaning: '사물이나 현상을 주의 깊게 살펴봄',
    example: '개미의 움직임을 며칠 동안 관찰했다.' },
  { id: 'h-gwanjeom2', type: 'hanja', word: '직관', hanja: '直觀',
    parts: [{ ch: '直', hun: '곧을', eum: '직' }, { ch: '觀', hun: '볼', eum: '관' }],
    literal: '곧바로 본다',
    meaning: '따져 보지 않고 대번에 알아차리는 것',
    example: '수학 문제를 직관으로 풀면 실수하기 쉽다.' },
  { id: 'h-chugjeong', type: 'hanja', word: '측정', hanja: '測定',
    parts: [{ ch: '測', hun: '잴', eum: '측' }, { ch: '定', hun: '정할', eum: '정' }],
    literal: '재어서 정한다',
    meaning: '길이·무게 등을 재어서 값을 정함',
    example: '실험 전에 물의 온도를 측정했다.' },
  { id: 'h-yeonron', type: 'hanja', word: '연역', hanja: '演繹',
    parts: [{ ch: '演', hun: '펼', eum: '연' }, { ch: '繹', hun: '풀어낼', eum: '역' }],
    literal: '펼쳐서 풀어낸다',
    meaning: '일반 원리에서 개별 사실을 이끌어 내는 추론',
    example: '모든 사람은 죽는다에서 시작하는 연역 추론.' },
  { id: 'h-gwinap', type: 'hanja', word: '귀납', hanja: '歸納',
    parts: [{ ch: '歸', hun: '돌아갈', eum: '귀' }, { ch: '納', hun: '들일', eum: '납' }],
    literal: '모아서 들인다',
    meaning: '여러 사례를 모아 일반 법칙을 이끌어 냄',
    example: '관찰 결과를 모아 귀납으로 결론을 세웠다.' },
  { id: 'h-geungeo', type: 'hanja', word: '근거', hanja: '根據',
    parts: [{ ch: '根', hun: '뿌리', eum: '근' }, { ch: '據', hun: '의거할', eum: '거' }],
    literal: '뿌리로 삼아 의지한다',
    meaning: '주장이 기대고 있는 바탕이나 이유',
    example: '주장에는 반드시 근거가 따라야 한다.' },
  { id: 'h-jeungmyeong', type: 'hanja', word: '증명', hanja: '證明',
    parts: [{ ch: '證', hun: '증거', eum: '증' }, { ch: '明', hun: '밝을', eum: '명' }],
    literal: '증거로 밝힌다',
    meaning: '사실이나 결론이 참임을 밝히는 일',
    example: '피타고라스 정리를 그림으로 증명했다.' },
  { id: 'h-banbak', type: 'hanja', word: '반박', hanja: '反駁',
    parts: [{ ch: '反', hun: '돌이킬', eum: '반' }, { ch: '駁', hun: '논박할', eum: '박' }],
    literal: '되받아 논박한다',
    meaning: '남의 의견에 반대하여 잘못을 지적함',
    example: '상대의 근거가 약하다며 조목조목 반박했다.' },
  { id: 'h-jeonhwan', type: 'hanja', word: '전환', hanja: '轉換',
    parts: [{ ch: '轉', hun: '구를', eum: '전' }, { ch: '換', hun: '바꿀', eum: '환' }],
    literal: '굴려서 바꾼다',
    meaning: '방향이나 상태를 다른 것으로 바꿈',
    example: '분위기 전환을 위해 잠시 쉬었다.' },
  { id: 'h-yeonghyang', type: 'hanja', word: '영향', hanja: '影響',
    parts: [{ ch: '影', hun: '그림자', eum: '영' }, { ch: '響', hun: '울릴', eum: '향' }],
    literal: '그림자처럼 따라오고 메아리처럼 울린다',
    meaning: '어떤 것이 다른 것에 미치는 작용',
    example: '기후 변화는 농사에 큰 영향을 준다.' },
  { id: 'h-hwangyeong', type: 'hanja', word: '환경', hanja: '環境',
    parts: [{ ch: '環', hun: '고리', eum: '환' }, { ch: '境', hun: '지경', eum: '경' }],
    literal: '둘러싼 경계',
    meaning: '생물을 둘러싸고 영향을 주는 조건',
    example: '깨끗한 환경에서 자란 나무가 튼튼하다.' },
  { id: 'h-jaewon', type: 'hanja', word: '자원', hanja: '資源',
    parts: [{ ch: '資', hun: '재물', eum: '자' }, { ch: '源', hun: '근원', eum: '원' }],
    literal: '재물의 근원',
    meaning: '생산에 쓰이는 물자나 힘의 원천',
    example: '물은 아껴 써야 할 소중한 자원이다.' },
  { id: 'h-sunhwan', type: 'hanja', word: '순환', hanja: '循環',
    parts: [{ ch: '循', hun: '돌', eum: '순' }, { ch: '環', hun: '고리', eum: '환' }],
    literal: '고리를 따라 돈다',
    meaning: '주기적으로 돌아 제자리로 오는 일',
    example: '물은 증발과 비로 순환한다.' },
  { id: 'h-gyunhyeong', type: 'hanja', word: '균형', hanja: '均衡',
    parts: [{ ch: '均', hun: '고를', eum: '균' }, { ch: '衡', hun: '저울대', eum: '형' }],
    literal: '저울이 고르다',
    meaning: '어느 쪽으로도 기울지 않고 고른 상태',
    example: '공부와 운동의 균형을 지켰다.' },
  { id: 'h-galdeung', type: 'hanja', word: '갈등', hanja: '葛藤',
    parts: [{ ch: '葛', hun: '칡', eum: '갈' }, { ch: '藤', hun: '등나무', eum: '등' }],
    literal: '칡과 등나무가 서로 얽힘',
    meaning: '서로 부딪쳐 얽힌 어려운 상태',
    example: '두 인물의 갈등이 이야기를 이끈다.' },
  { id: 'h-hyeopryeok', type: 'hanja', word: '협력', hanja: '協力',
    parts: [{ ch: '協', hun: '화합할', eum: '협' }, { ch: '力', hun: '힘', eum: '력' }],
    literal: '힘을 합한다',
    meaning: '힘을 모아 서로 도움',
    example: '모둠원들의 협력으로 과제를 마쳤다.' },
  { id: 'h-chaegim', type: 'hanja', word: '책임', hanja: '責任',
    parts: [{ ch: '責', hun: '꾸짖을', eum: '책' }, { ch: '任', hun: '맡길', eum: '임' }],
    literal: '맡은 일을 꾸짖어 묻는다',
    meaning: '맡아서 해야 할 임무나 그에 따른 부담',
    example: '자기가 한 말에는 책임이 따른다.' },
  { id: 'h-gwonri', type: 'hanja', word: '권리', hanja: '權利',
    parts: [{ ch: '權', hun: '권세', eum: '권' }, { ch: '利', hun: '이로울', eum: '리' }],
    literal: '누릴 수 있는 힘과 이익',
    meaning: '당연히 누리거나 주장할 수 있는 자격',
    example: '모든 학생은 배울 권리가 있다.' },
  { id: 'h-uimu', type: 'hanja', word: '의무', hanja: '義務',
    parts: [{ ch: '義', hun: '옳을', eum: '의' }, { ch: '務', hun: '힘쓸', eum: '무' }],
    literal: '옳은 일에 힘쓴다',
    meaning: '마땅히 해야 할 일',
    example: '권리에는 의무가 함께 따른다.' },
  { id: 'h-jedo', type: 'hanja', word: '제도', hanja: '制度',
    parts: [{ ch: '制', hun: '마를', eum: '제' }, { ch: '度', hun: '법도', eum: '도' }],
    literal: '마름질해 정한 법도',
    meaning: '사회가 함께 지키기로 정한 규칙과 틀',
    example: '학교 급식은 오래된 제도다.' },
  { id: 'h-hyeonsang', type: 'hanja', word: '현상', hanja: '現象',
    parts: [{ ch: '現', hun: '나타날', eum: '현' }, { ch: '象', hun: '모양', eum: '상' }],
    literal: '나타난 모양',
    meaning: '눈에 보이거나 관찰되는 사물의 모습',
    example: '무지개는 빛이 꺾여 생기는 현상이다.' },
  { id: 'h-bonjil', type: 'hanja', word: '본질', hanja: '本質',
    parts: [{ ch: '本', hun: '근본', eum: '본' }, { ch: '質', hun: '바탕', eum: '질' }],
    literal: '근본이 되는 바탕',
    meaning: '그것을 그것답게 만드는 가장 중요한 성질',
    example: '겉모습보다 본질을 봐야 한다.' },
  { id: 'h-gaenyeom', type: 'hanja', word: '개념', hanja: '槪念',
    parts: [{ ch: '槪', hun: '대개', eum: '개' }, { ch: '念', hun: '생각', eum: '념' }],
    literal: '대체로 잡은 생각',
    meaning: '여러 대상에서 공통된 것을 뽑아 만든 생각',
    example: '먼저 개념을 정확히 잡아야 문제가 풀린다.' },
  { id: 'h-bunryu', type: 'hanja', word: '분류', hanja: '分類',
    parts: [{ ch: '分', hun: '나눌', eum: '분' }, { ch: '類', hun: '무리', eum: '류' }],
    literal: '무리로 나눈다',
    meaning: '공통점에 따라 갈래를 지어 나눔',
    example: '도서관 책은 주제별로 분류되어 있다.' },
  { id: 'h-bigyo', type: 'hanja', word: '비교', hanja: '比較',
    parts: [{ ch: '比', hun: '견줄', eum: '비' }, { ch: '較', hun: '견줄', eum: '교' }],
    literal: '견주고 또 견준다',
    meaning: '둘 이상을 맞대어 공통점과 차이를 살핌',
    example: '두 실험 결과를 비교해 보았다.' },
  { id: 'h-yoyak', type: 'hanja', word: '요약', hanja: '要約',
    parts: [{ ch: '要', hun: '요긴할', eum: '요' }, { ch: '約', hun: '묶을', eum: '약' }],
    literal: '요긴한 것만 묶는다',
    meaning: '중요한 것만 골라 짧게 간추림',
    example: '읽은 글을 세 문장으로 요약했다.' },
  { id: 'h-siljeung', type: 'hanja', word: '실증', hanja: '實證',
    parts: [{ ch: '實', hun: '열매', eum: '실' }, { ch: '證', hun: '증거', eum: '증' }],
    literal: '실제 증거로 보인다',
    meaning: '실제 사실이나 실험으로 증명함',
    example: '가설을 실험으로 실증했다.' },
  { id: 'h-gaseol', type: 'hanja', word: '가설', hanja: '假說',
    parts: [{ ch: '假', hun: '거짓', eum: '가' }, { ch: '說', hun: '말씀', eum: '설' }],
    literal: '임시로 세운 말',
    meaning: '검증하기 전에 임시로 세운 설명',
    example: '가설을 세우고 실험으로 확인한다.' },
  { id: 'h-oryu', type: 'hanja', word: '오류', hanja: '誤謬',
    parts: [{ ch: '誤', hun: '그르칠', eum: '오' }, { ch: '謬', hun: '그릇될', eum: '류' }],
    literal: '그르치고 그릇되다',
    meaning: '생각이나 계산이 잘못된 것',
    example: '계산 과정에 작은 오류가 있었다.' },
  { id: 'h-boan', type: 'hanja', word: '보완', hanja: '補完',
    parts: [{ ch: '補', hun: '기울', eum: '보' }, { ch: '完', hun: '완전할', eum: '완' }],
    literal: '기워서 완전하게 한다',
    meaning: '모자란 것을 채워 온전하게 함',
    example: '부족한 부분을 자료로 보완했다.' },

  /* ── 고유어 추가 30 ──────────────────────── */
  { id: 'n-buchugida', type: 'native', word: '부추기다',
    scene: '옆에서 등을 툭툭 밀며 "해 봐, 해 봐" 하는 장면',
    syn: ['꼬드기다', '충동질하다'],
    meaning: '남을 들쑤셔 어떤 일을 하게 만들다',
    example: '친구가 부추겨서 무대에 올라갔다.' },
  { id: 'n-tteoreomida', type: 'native', word: '떠올리다',
    scene: '물에 잠긴 공이 수면 위로 떠오르듯 기억이 쑥 올라오는 장면',
    syn: ['상기하다', '생각해 내다'],
    meaning: '기억을 되살려 생각해 내다',
    example: '어제 배운 단어를 떠올려 보았다.' },
  { id: 'n-jitgutda', type: 'native', word: '짓궂다',
    scene: '몰래 의자를 빼놓고 킥킥 웃는 장난꾸러기',
    syn: ['짓궂다', '얄궂다'],
    meaning: '남을 곤란하게 할 만큼 장난이 심하다',
    example: '짓궂은 농담에 friends가 웃음을 터뜨렸다.' },
  { id: 'n-eosaekhada', type: 'native', word: '어색하다',
    scene: '처음 만난 사람과 엘리베이터에 단둘이 서 있는 순간',
    syn: ['서먹하다', '부자연스럽다'],
    meaning: '자연스럽지 못하고 서먹하다',
    example: '첫 인사는 늘 조금 어색하다.' },
  { id: 'n-neuggeutada', type: 'native', word: '느긋하다',
    scene: '해먹에 누워 다리를 흔들며 구름을 보는 오후',
    syn: ['여유롭다', '태평하다'],
    meaning: '서두르지 않고 마음이 넉넉하다',
    example: '시험이 끝나 느긋한 주말을 보냈다.' },
  { id: 'n-jogeupada', type: 'native', word: '조급하다',
    scene: '신호가 안 바뀌는데 발을 동동 구르는 모습',
    syn: ['성급하다', '초조하다'],
    meaning: '참을성 없이 몹시 급하다',
    example: '조급하게 굴다가 답을 잘못 썼다.' },
  { id: 'n-kkomkkomhada', type: 'native', word: '꼼꼼하다',
    scene: '자로 잰 듯 줄을 맞춰 필기하는 공책',
    syn: ['세심하다', '빈틈없다'],
    meaning: '빈틈없이 자세하고 차분하다',
    example: '꼼꼼하게 검토했더니 실수가 없었다.' },
  { id: 'n-heosulhada', type: 'native', word: '허술하다',
    scene: '못이 빠져 삐걱거리는 낡은 울타리',
    syn: ['엉성하다', '부실하다'],
    meaning: '치밀하지 못해 빈틈이 있다',
    example: '계획이 허술해서 중간에 막혔다.' },
  { id: 'n-tteotteothada', type: 'native', word: '떳떳하다',
    scene: '고개를 들고 어깨를 편 채 걸어 나오는 뒷모습',
    syn: ['당당하다', '거리낌 없다'],
    meaning: '숨길 것이 없어 마음이 당당하다',
    example: '정직하게 했으니 떳떳하다.' },
  { id: 'n-mimanghada', type: 'native', word: '미덥다',
    scene: '무거운 짐을 말없이 들어 주는 든든한 어깨',
    syn: ['믿음직하다', '든든하다'],
    meaning: '믿을 만하다',
    example: '맡겨 두면 미더운 친구다.' },
  { id: 'n-sseulmoitda', type: 'native', word: '쓸모없다',
    scene: '고장 나서 서랍 구석에 처박힌 낡은 리모컨',
    syn: ['무용하다', '소용없다'],
    meaning: '쓸 만한 가치가 없다',
    example: '버릴 뻔한 물건이 알고 보니 쓸모없지 않았다.' },
  { id: 'n-dodeuraji', type: 'native', word: '도드라지다',
    scene: '회색 돌 사이에서 혼자 새빨간 단풍잎',
    syn: ['두드러지다', '눈에 띄다'],
    meaning: '겉으로 뚜렷하게 드러나다',
    example: '그림에서 붉은색이 유난히 도드라졌다.' },
  { id: 'n-eoulrida', type: 'native', word: '어울리다',
    scene: '퍼즐 조각이 딱 맞아 들어가는 순간',
    syn: ['조화되다', '맞아떨어지다'],
    meaning: '서로 잘 맞아 조화를 이루다',
    example: '파란 셔츠가 얼굴색과 잘 어울린다.' },
  { id: 'n-beotida', type: 'native', word: '버티다',
    scene: '거센 바람에도 뿌리를 박고 서 있는 나무',
    syn: ['견디다', '지탱하다'],
    meaning: '어려움을 참고 견뎌 내다',
    example: '마지막 한 문제까지 버텨서 풀었다.' },
  { id: 'n-mumeotgeorida', type: 'native', word: '머뭇거리다',
    scene: '손을 들까 말까 하며 팔을 반쯤 올렸다 내리는 모습',
    syn: ['주저하다', '망설이다'],
    meaning: '선뜻 하지 못하고 자꾸 망설이다',
    example: '대답을 못 하고 한참 머뭇거렸다.' },
  { id: 'n-eongkeuda', type: 'native', word: '엉기다',
    scene: '식은 죽이 한 덩어리로 굳어 숟가락에 붙는 모습',
    syn: ['엉키다', '뭉치다'],
    meaning: '한데 뭉쳐 굳거나 얽히다',
    example: '실이 엉겨서 풀기 어려웠다.' },
  { id: 'n-nunchi', type: 'native', word: '눈치',
    scene: '말없이 표정만 보고 분위기를 읽어 내는 순간',
    syn: ['기색', '낌새'],
    meaning: '남의 마음이나 분위기를 알아채는 힘',
    example: '눈치가 빨라 먼저 도와주었다.' },
  { id: 'n-mitbatchim', type: 'native', word: '밑바탕',
    scene: '그림을 그리기 전에 먼저 칠해 두는 흰 바탕',
    syn: ['기초', '토대'],
    meaning: '어떤 것의 근본이 되는 바탕',
    example: '기초 어휘가 독해의 밑바탕이다.' },
  { id: 'n-teumteumi', type: 'native', word: '틈틈이',
    scene: '벽돌 사이 좁은 틈마다 자라난 작은 풀',
    syn: ['짬짬이', '수시로'],
    meaning: '겨를이 날 때마다 조금씩',
    example: '쉬는 시간마다 틈틈이 단어를 외웠다.' },
  { id: 'n-jureojulmuk', type: 'native', word: '줄곧',
    scene: '출발선부터 결승선까지 한 번도 안 멈춘 주자',
    syn: ['내내', '계속'],
    meaning: '끊이지 않고 내내',
    example: '아침부터 줄곧 비가 내렸다.' },
  { id: 'n-daedanhi', type: 'native', word: '대뜸',
    scene: '문을 열자마자 인사도 없이 바로 본론을 꺼내는 사람',
    syn: ['다짜고짜', '단박에'],
    meaning: '앞뒤 없이 그 자리에서 바로',
    example: '들어오자마자 대뜸 이유를 물었다.' },
  { id: 'n-gyeoulhada', type: 'native', word: '겨루다',
    scene: '팔씨름으로 팽팽하게 맞선 두 팔',
    syn: ['다투다', '경쟁하다'],
    meaning: '서로 이기려고 힘이나 실력을 다투다',
    example: '두 팀이 결승에서 겨루었다.' },
  { id: 'n-doedolabuda', type: 'native', word: '되돌아보다',
    scene: '언덕 위에서 걸어온 길을 뒤돌아보는 뒷모습',
    syn: ['회고하다', '돌이키다'],
    meaning: '지난 일을 다시 생각해 보다',
    example: '한 학기를 되돌아보며 계획을 세웠다.' },
  { id: 'n-ttokbaro', type: 'native', word: '똑바로',
    scene: '자를 대고 그은 것처럼 곧게 뻗은 선',
    syn: ['곧게', '바르게'],
    meaning: '비뚤어지지 않고 곧게',
    example: '허리를 똑바로 펴고 앉았다.' },
  { id: 'n-eoseolpeuda', type: 'native', word: '어설프다',
    scene: '처음 잡아 본 젓가락이 자꾸 미끄러지는 손',
    syn: ['서투르다', '엉성하다'],
    meaning: '익숙하지 못해 서투르다',
    example: '어설픈 솜씨였지만 끝까지 만들었다.' },
  { id: 'n-nunbusida', type: 'native', word: '눈부시다',
    scene: '한겨울 눈밭에 햇빛이 쏟아져 눈을 못 뜨는 순간',
    syn: ['찬란하다', '빛나다'],
    meaning: '빛이 강해 바로 보기 어렵다, 매우 훌륭하다',
    example: '올해 그 선수의 활약은 눈부셨다.' },
  { id: 'n-seolpeuda', type: 'native', word: '섣부르다',
    scene: '반죽이 덜 익었는데 뚜껑을 열어 버린 냄비',
    syn: ['성급하다', '어설프다'],
    meaning: '설익어서 조심성 없이 급하다',
    example: '섣부른 판단은 실수를 부른다.' },
  { id: 'n-gadeukhada', type: 'native', word: '가득하다',
    scene: '물이 찰랑찰랑 넘치기 직전인 컵',
    syn: ['꽉 차다', '충만하다'],
    meaning: '빈 곳 없이 꽉 차 있다',
    example: '교실이 웃음소리로 가득했다.' },
  { id: 'n-mitgeurojida', type: 'native', word: '미끄러지다',
    scene: '얼음판에 발을 딛자마자 쭉 밀려나는 발',
    syn: ['빗나가다', '밀리다'],
    meaning: '미끄러워 밀려 나가다, 시험에 떨어지다',
    example: '빙판에서 미끄러질 뻔했다.' },
  { id: 'n-chagunchagun', type: 'native', word: '차근차근',
    scene: '계단을 한 칸씩 또박또박 밟아 올라가는 발걸음',
    syn: ['하나하나', '천천히'],
    meaning: '서두르지 않고 순서대로 조리 있게',
    example: '차근차근 설명하니 모두 이해했다.' },

  /* ── 영어 추가 30 ────────────────────────── */
  { id: 'e-analyze', type: 'english', word: 'analyze', pron: '애널라이즈',
    cue: '"애? 널 라이즈(쪼개)!" 잘게 쪼개 살핀다',
    scene: '레고를 조각조각 분해해 놓고 들여다보는 장면',
    meaning: '분석하다',
    example: 'Let’s analyze the data together.' },
  { id: 'e-describe', type: 'english', word: 'describe', pron: '디스크라이브',
    cue: 'scribe(쓰다) — 아래로 죽 써 내려가며 설명',
    scene: '본 것을 공책에 줄줄 받아 적는 기자',
    root: { stem: 'scrib', sense: '쓰다', family: ['script', 'subscribe'] },
    meaning: '묘사하다, 설명하다',
    example: 'Describe what you saw in the picture.' },
  { id: 'e-explain', type: 'english', word: 'explain', pron: '익스플레인',
    cue: 'ex(밖) + plain(평평) — 밖으로 평평하게 펴서 보여 준다',
    scene: '구겨진 지도를 쫙 펴서 길을 짚어 주는 장면',
    meaning: '설명하다',
    example: 'Can you explain this rule again?' },
  { id: 'e-suggest', type: 'english', word: 'suggest', pron: '서제스트',
    cue: '"서서 제스처로" 이렇게 해 보라고 권한다',
    scene: '손짓으로 다른 길을 가리키며 권하는 모습',
    meaning: '제안하다',
    example: 'I suggest we start with the easy part.' },
  { id: 'e-require', type: 'english', word: 'require', pron: '리콰이어',
    cue: 're(다시) + quire(구하다) — 꼭 있어야 해서 거듭 구한다',
    scene: '입장하려는데 "표가 꼭 필요합니다" 하고 막는 직원',
    meaning: '필요로 하다, 요구하다',
    example: 'This job requires patience.' },
  { id: 'e-provide', type: 'english', word: 'provide', pron: '프로바이드',
    cue: 'pro(앞) + vid(보다) — 미리 내다보고 챙겨 준다',
    scene: '소풍 전날 도시락을 미리 싸 두는 부모님',
    root: { stem: 'vid', sense: '보다', family: ['video', 'evidence'] },
    meaning: '제공하다',
    example: 'The school provides free lunch.' },
  { id: 'e-improve', type: 'english', word: 'improve', pron: '임프루브',
    cue: '"임(in) + prove" — 안으로 더 좋아짐을 증명한다',
    scene: '성적 그래프가 한 칸씩 위로 올라가는 장면',
    meaning: '개선하다, 나아지다',
    example: 'Reading every day improves your vocabulary.' },
  { id: 'e-reduce', type: 'english', word: 'reduce', pron: '리듀스',
    cue: 're(뒤) + duce(이끌다) — 뒤로 끌어 줄인다',
    scene: '풍선에서 바람을 빼 작아지게 하는 장면',
    root: { stem: 'duc', sense: '이끌다', family: ['produce', 'introduce'] },
    meaning: '줄이다',
    example: 'We should reduce plastic waste.' },
  { id: 'e-increase', type: 'english', word: 'increase', pron: '인크리스',
    cue: '"인(in) + 크리(크게)" — 안에서 크게 불어난다',
    scene: '작은 눈덩이가 굴러가며 점점 커지는 장면',
    meaning: '증가하다, 늘리다',
    example: 'The number of readers increased sharply.' },
  { id: 'e-affect', type: 'english', word: 'affect', pron: '어펙트',
    cue: 'af(향해) + fect(만들다) — 다가가 변화를 만든다',
    scene: '돌 하나가 물에 떨어져 파문이 번지는 장면',
    root: { stem: 'fect', sense: '만들다', family: ['effect', 'perfect'] },
    meaning: '영향을 미치다',
    example: 'Sleep affects how well you remember.' },
  { id: 'e-cause', type: 'english', word: 'cause', pron: '코즈',
    cue: '"코즈(때문에)" — 그것 때문에 벌어진다',
    scene: '도미노 첫 조각이 쓰러지자 줄줄이 넘어지는 장면',
    meaning: '원인, 일으키다',
    example: 'Heavy rain caused the delay.' },
  { id: 'e-result', type: 'english', word: 'result', pron: '리절트',
    cue: 're(다시) + sult(뛰다) — 튀어나온 결과',
    scene: '실험이 끝나고 화면에 숫자가 탁 튀어나오는 장면',
    meaning: '결과, 결과로 생기다',
    example: 'The result surprised everyone.' },
  { id: 'e-observe2', type: 'english', word: 'measure', pron: '메저',
    cue: '"메(매) + 저(자)" — 자를 매어 잰다',
    scene: '줄자를 팽팽히 당겨 길이를 재는 손',
    meaning: '측정하다, 치수',
    example: 'Measure the length before you cut.' },
  { id: 'e-decide', type: 'english', word: 'decide', pron: '디사이드',
    cue: 'de(떼어) + cide(자르다) — 잘라서 정한다',
    scene: '갈림길에서 한쪽을 가위로 딱 잘라 내는 장면',
    meaning: '결정하다',
    example: 'We decided to start early.' },
  { id: 'e-consider', type: 'english', word: 'consider', pron: '컨시더',
    cue: '"큰 시더(생각)" — 크게 두루 생각한다',
    scene: '별자리를 하나하나 짚어 가며 오래 헤아리는 사람',
    meaning: '고려하다, 여기다',
    example: 'Consider both sides before you judge.' },
  { id: 'e-realize', type: 'english', word: 'realize', pron: '리얼라이즈',
    cue: 'real(진짜) — 진짜였구나 하고 깨닫는다',
    scene: '머리 위에 전구가 반짝 켜지는 순간',
    meaning: '깨닫다, 실현하다',
    example: 'I realized my mistake too late.' },
  { id: 'e-recognize', type: 'english', word: 'recognize', pron: '레커그나이즈',
    cue: 're(다시) + cogn(알다) — 다시 보고 알아본다',
    scene: '오랜만에 만난 친구 얼굴을 알아보고 손을 드는 장면',
    root: { stem: 'cogn', sense: '알다', family: ['cognitive', 'recognition'] },
    meaning: '알아보다, 인정하다',
    example: 'I didn’t recognize him with short hair.' },
  { id: 'e-remain', type: 'english', word: 'remain', pron: '리메인',
    cue: 're(계속) + main(남다) — 계속 남아 있다',
    scene: '모두 떠난 교실에 홀로 남은 의자 하나',
    meaning: '남다, 계속 ~이다',
    example: 'Only three cookies remain.' },
  { id: 'e-avoid', type: 'english', word: 'avoid', pron: '어보이드',
    cue: 'void(빈 곳) — 비워 두고 피한다',
    scene: '웅덩이를 폴짝 뛰어넘어 피해 가는 발',
    meaning: '피하다',
    example: 'Avoid studying right before you sleep.' },
  { id: 'e-achieve2', type: 'english', word: 'obtain', pron: '옵테인',
    cue: 'ob(향해) + tain(붙잡다) — 향해 가서 붙잡는다',
    scene: '높은 선반의 상자를 까치발로 잡아 내리는 장면',
    root: { stem: 'tain', sense: '붙잡다', family: ['contain', 'maintain'] },
    meaning: '얻다, 획득하다',
    example: 'She obtained a perfect score.' },
  { id: 'e-contain', type: 'english', word: 'contain', pron: '컨테인',
    cue: 'con(함께) + tain(붙잡다) — 안에 담아 붙들고 있다',
    scene: '컨테이너 안에 짐이 가득 담겨 있는 장면',
    root: { stem: 'tain', sense: '붙잡다', family: ['obtain', 'maintain'] },
    meaning: '포함하다, 담고 있다',
    example: 'This juice contains no sugar.' },
  { id: 'e-appear', type: 'english', word: 'appear', pron: '어피어',
    cue: '"어? 피어(났다)!" 불쑥 나타난다',
    scene: '땅에서 새싹이 쑥 올라오는 장면',
    meaning: '나타나다, ~처럼 보이다',
    example: 'A rainbow appeared after the rain.' },
  { id: 'e-disappear', type: 'english', word: 'disappear', pron: '디서피어',
    cue: 'dis(반대) + appear(나타나다) — 반대로 사라진다',
    scene: '마술사가 보를 걷자 상자가 사라진 무대',
    meaning: '사라지다',
    example: 'The stars disappear at sunrise.' },
  { id: 'e-similar', type: 'english', word: 'similar', pron: '시밀러',
    cue: '"시(같은) + 밀러(거울)" — 거울처럼 닮았다',
    scene: '쌍둥이가 나란히 서서 같은 포즈를 한 장면',
    meaning: '비슷한',
    example: 'Their handwriting looks similar.' },
  { id: 'e-different', type: 'english', word: 'various', pron: '베리어스',
    cue: 'vary(변하다) — 여러 가지로 변한다',
    scene: '팔레트에 색이 열두 가지 짜여 있는 장면',
    meaning: '다양한',
    example: 'The library has various kinds of books.' },
  { id: 'e-obvious', type: 'english', word: 'obvious', pron: '아비어스',
    cue: 'ob(앞에) + via(길) — 길 앞에 뻔히 놓여 있다',
    scene: '길 한복판에 커다란 바위가 떡 놓인 장면',
    meaning: '분명한, 뻔한',
    example: 'The answer was obvious to everyone.' },
  { id: 'e-accurate', type: 'english', word: 'accurate', pron: '애큐릿',
    cue: 'cure(주의) — 주의를 다해 딱 맞힌다',
    scene: '화살이 과녁 한가운데에 정확히 꽂힌 장면',
    meaning: '정확한',
    example: 'His measurement was surprisingly accurate.' },
  { id: 'e-complex', type: 'english', word: 'complex', pron: '컴플렉스',
    cue: 'com(함께) + plex(엮다) — 여러 겹으로 얽혔다',
    scene: '실이 사방으로 얽혀 풀기 힘든 뭉치',
    meaning: '복잡한',
    example: 'The problem is more complex than it looks.' },
  { id: 'e-familiar', type: 'english', word: 'familiar', pron: '퍼밀리어',
    cue: 'family(가족) — 가족처럼 익숙하다',
    scene: '매일 지나는 골목이 눈 감고도 그려지는 장면',
    meaning: '익숙한, 낯익은',
    example: 'This song sounds familiar.' },
  { id: 'e-effort2', type: 'english', word: 'attempt', pron: '어템프트',
    cue: 'temp(시도) — 한 번 해 보려고 손을 뻗는다',
    scene: '높은 봉을 잡으려 몇 번이고 뛰어오르는 모습',
    meaning: '시도하다, 시도',
    example: 'She made three attempts before succeeding.' }
];

if (typeof module !== 'undefined' && module.exports) module.exports = { WB_WORDS };
