'use strict';
/* WB 워드브레인 — 시드 단어 데이터
   type: hanja(한자어) | native(고유어) | english(영어)
   level: L1(7세~초2) | L2(초3~6) | L3(중1~3) | L4(고1~3) — 진로독서와 같은 눈금
   공통: id, type, level, word, meaning, example
   hanja: hanja, parts[{ch,hun,eum}], literal(조립 뜻)
   english: pron, cue(키워드 연상), scene(연상 장면), root{stem,sense,family[]}(선택)
   native: scene(이미지 연상 장면), syn[](유의어) */
var WB_WORDS = [
  /* ── 한자어 15 ─────────────────────────────── */
  { id: 'h-gwancheuk', type: 'hanja', level: 'L3', word: '관측', hanja: '觀測',
    parts: [{ ch: '觀', hun: '볼', eum: '관' }, { ch: '測', hun: '잴', eum: '측' }],
    literal: '보고 잰다',
    meaning: '눈이나 기계로 자연 현상을 자세히 살펴 재는 것',
    example: '천문대에서 별의 움직임을 관측했다.' },
  { id: 'h-gwanjeom', type: 'hanja', level: 'L3', word: '관점', hanja: '觀點',
    parts: [{ ch: '觀', hun: '볼', eum: '관' }, { ch: '點', hun: '점', eum: '점' }],
    literal: '바라보는 지점',
    meaning: '사물이나 사건을 바라보는 자기만의 자리, 시각',
    example: '같은 사건도 관점에 따라 다르게 보인다.' },
  { id: 'h-gaekgwan', type: 'hanja', level: 'L3', word: '객관', hanja: '客觀',
    parts: [{ ch: '客', hun: '손님', eum: '객' }, { ch: '觀', hun: '볼', eum: '관' }],
    literal: '손님처럼 본다',
    meaning: '내 감정에서 떨어져 제3자의 눈으로 보는 것',
    example: '심판은 객관적인 눈으로 판정해야 한다.' },
  { id: 'h-jugwan', type: 'hanja', level: 'L3', word: '주관', hanja: '主觀',
    parts: [{ ch: '主', hun: '주인', eum: '주' }, { ch: '觀', hun: '볼', eum: '관' }],
    literal: '주인으로서 본다',
    meaning: '자기 생각과 느낌을 중심으로 보는 것',
    example: '일기에는 나의 주관이 그대로 담긴다.' },
  { id: 'h-churon', type: 'hanja', level: 'L4', word: '추론', hanja: '推論',
    parts: [{ ch: '推', hun: '밀', eum: '추' }, { ch: '論', hun: '논할', eum: '론' }],
    literal: '밀고 나가 논한다',
    meaning: '아는 사실을 바탕으로 모르는 것을 미루어 생각함',
    example: '발자국의 크기를 보고 범인의 키를 추론했다.' },
  { id: 'h-nonjeung', type: 'hanja', level: 'L4', word: '논증', hanja: '論證',
    parts: [{ ch: '論', hun: '논할', eum: '론' }, { ch: '證', hun: '증거', eum: '증' }],
    literal: '증거를 대어 논한다',
    meaning: '이유와 증거를 들어 주장이 옳음을 밝히는 것',
    example: '글쓴이는 세 가지 근거로 주장을 논증했다.' },
  { id: 'h-banron', type: 'hanja', level: 'L3', word: '반론', hanja: '反論',
    parts: [{ ch: '反', hun: '돌이킬', eum: '반' }, { ch: '論', hun: '논할', eum: '론' }],
    literal: '되돌려 논한다',
    meaning: '상대의 주장에 맞서 되받아치는 주장',
    example: '토론에서 상대의 반론에 침착하게 답했다.' },
  { id: 'h-mosun', type: 'hanja', level: 'L4', word: '모순', hanja: '矛盾',
    parts: [{ ch: '矛', hun: '창', eum: '모' }, { ch: '盾', hun: '방패', eum: '순' }],
    literal: '무엇이든 뚫는 창 + 무엇이든 막는 방패',
    meaning: '말이나 행동의 앞뒤가 서로 맞지 않음',
    example: '일찍 자라면서 밤새 공부하라는 말은 모순이다.' },
  { id: 'h-tadang', type: 'hanja', level: 'L4', word: '타당', hanja: '妥當',
    parts: [{ ch: '妥', hun: '온당할', eum: '타' }, { ch: '當', hun: '마땅', eum: '당' }],
    literal: '온당하고 마땅하다',
    meaning: '이치에 맞아 옳다고 할 만함',
    example: '그 주장은 근거가 충분해서 타당하다.' },
  { id: 'h-jeonje', type: 'hanja', level: 'L3', word: '전제', hanja: '前提',
    parts: [{ ch: '前', hun: '앞', eum: '전' }, { ch: '提', hun: '끌', eum: '제' }],
    literal: '앞에 끌어다 놓음',
    meaning: '어떤 주장이 성립하도록 미리 깔아 두는 조건',
    example: '약속은 지킨다는 전제 위에서 이루어진다.' },
  { id: 'h-hamchuk', type: 'hanja', level: 'L4', word: '함축', hanja: '含蓄',
    parts: [{ ch: '含', hun: '머금을', eum: '함' }, { ch: '蓄', hun: '쌓을', eum: '축' }],
    literal: '머금고 쌓아 둔다',
    meaning: '겉으로 다 말하지 않고 속에 담아 둔 뜻',
    example: '이 시의 마지막 행은 깊은 슬픔을 함축한다.' },
  { id: 'h-seongchal', type: 'hanja', level: 'L4', word: '성찰', hanja: '省察',
    parts: [{ ch: '省', hun: '살필', eum: '성' }, { ch: '察', hun: '살필', eum: '찰' }],
    literal: '살피고 또 살핀다',
    meaning: '자기 마음과 행동을 돌이켜 깊이 살펴봄',
    example: '하루를 마치며 나의 말과 행동을 성찰했다.' },
  { id: 'h-jeolchung', type: 'hanja', level: 'L4', word: '절충', hanja: '折衷',
    parts: [{ ch: '折', hun: '꺾을', eum: '절' }, { ch: '衷', hun: '속마음', eum: '충' }],
    literal: '양쪽을 꺾어 가운데 마음을 취한다',
    meaning: '서로 다른 의견에서 좋은 점을 골라 알맞게 맞춤',
    example: '두 팀의 계획을 절충해 새로운 안을 만들었다.' },
  { id: 'h-chegye', type: 'hanja', level: 'L3', word: '체계', hanja: '體系',
    parts: [{ ch: '體', hun: '몸', eum: '체' }, { ch: '系', hun: '이어맬', eum: '계' }],
    literal: '한 몸처럼 이어 묶음',
    meaning: '낱낱의 것이 짜임새 있게 이어진 전체 틀',
    example: '도서관의 책은 분류 체계에 따라 꽂혀 있다.' },
  { id: 'h-mumo', type: 'hanja', level: 'L3', word: '무모', hanja: '無謀',
    parts: [{ ch: '無', hun: '없을', eum: '무' }, { ch: '謀', hun: '꾀할', eum: '모' }],
    literal: '꾀함(계획)이 없다',
    meaning: '앞뒤 계획 없이 마구 덤빔',
    example: '준비 없이 겨울 산에 오르는 것은 무모하다.' },

  /* ── 영어 15 ──────────────────────────────── */
  { id: 'e-observe', type: 'english', level: 'L3', word: 'observe', pron: '옵저브',
    cue: '"옵! 저(것) 봐!"',
    scene: '"옵! 저 봐!" 소리치며 돋보기로 자세히 들여다보는 장면',
    meaning: '관찰하다, 자세히 살펴보다',
    example: 'Scientists observe the stars every night.' },
  { id: 'e-predict', type: 'english', level: 'L3', word: 'predict', pron: '프리딕트',
    cue: '미리(pre) 말하다(dict)',
    scene: '일기예보관이 내일 날씨를 미리 말해 주는 장면',
    root: { stem: 'dict', sense: '말하다', family: ['dictionary', 'dictation'] },
    meaning: '예측하다',
    example: 'Can you predict tomorrow’s weather?' },
  { id: 'e-evidence', type: 'english', level: 'L3', word: 'evidence', pron: '에비던스',
    cue: 'vid = 보다 → 눈에 보이게 드러난 것',
    scene: '탐정이 돋보기로 진흙 위 발자국을 가리키는 장면',
    root: { stem: 'vid', sense: '보다', family: ['video', 'visible'] },
    meaning: '증거',
    example: 'The detective found new evidence.' },
  { id: 'e-conclude', type: 'english', level: 'L3', word: 'conclude', pron: '컨클루드',
    cue: '함께(con) 문을 닫다(clude) → 이야기를 닫다',
    scene: '"오늘 회의는 여기까지!" 하며 문을 닫는 장면',
    root: { stem: 'clude', sense: '닫다', family: ['include', 'exclude'] },
    meaning: '결론을 내리다, 끝맺다',
    example: 'The report concludes that exercise helps memory.' },
  { id: 'e-estimate', type: 'english', level: 'L4', word: 'estimate', pron: '에스티메이트',
    cue: 'S.T. 메이트(친구)가 값을 척 보고 어림잡는다',
    scene: '친구가 나무를 척 보더니 "한 10미터?" 하는 장면',
    meaning: '어림잡다, 추정하다',
    example: 'Can you estimate the height of that tree?' },
  { id: 'e-compare', type: 'english', level: 'L3', word: 'compare', pron: '컴페어',
    cue: '짝(pair)을 함께(com) 놓고 견주다',
    scene: '저울 양쪽에 사과와 배를 올려 견주는 장면',
    root: { stem: 'par', sense: '같은, 짝', family: ['pair', 'part'] },
    meaning: '비교하다',
    example: 'Compare the two pictures and find the differences.' },
  { id: 'e-examine', type: 'english', level: 'L4', word: 'examine', pron: '이그재민',
    cue: '"이그, 재 민(이)!" — 뭐든 자로 재 보는 민이',
    scene: '의사 선생님이 청진기로 구석구석 살피는 장면',
    meaning: '자세히 조사하다, 진찰하다',
    example: 'The doctor examined the patient carefully.' },
  { id: 'e-insist', type: 'english', level: 'L4', word: 'insist', pron: '인시스트',
    cue: '자기 주장 안(in)에 버티고 서다(sist)',
    scene: '팔짱을 끼고 "무조건 이거야!" 버티는 장면',
    root: { stem: 'sist', sense: '서다', family: ['assist', 'consist'] },
    meaning: '고집하다, 강하게 주장하다',
    example: 'She insisted that she was right.' },
  { id: 'e-persuade', type: 'english', level: 'L4', word: 'persuade', pron: '퍼수에이드',
    cue: '"퍼 줘!" 하며 마음을 얻는다',
    scene: '"아이스크림 퍼 줄게" 하며 동생 마음을 돌리는 장면',
    meaning: '설득하다',
    example: 'He persuaded his parents to buy a puppy.' },
  { id: 'e-achieve', type: 'english', level: 'L3', word: 'achieve', pron: '어치브',
    cue: '"아, 치익—" 결승선을 끊고 브이(V)!',
    scene: '결승선 테이프를 끊으며 브이를 그리는 장면',
    meaning: '이루다, 달성하다',
    example: 'She achieved her goal of reading 100 books.' },
  { id: 'e-purpose', type: 'english', level: 'L3', word: 'purpose', pron: '퍼포스',
    cue: '무대 위 모든 포즈(pose)에는 목적이 있다',
    scene: '안무가가 "이 포즈의 목적은?" 하고 묻는 장면',
    meaning: '목적',
    example: 'What is the purpose of this experiment?' },
  { id: 'e-method', type: 'english', level: 'L3', word: 'method', pron: '메소드',
    cue: '레시피대로 차근차근 — 요리엔 방법이 있다',
    scene: '레시피 순서를 손가락으로 짚으며 요리하는 장면',
    meaning: '방법, 방식',
    example: 'This is a new method for learning words.' },
  { id: 'e-region', type: 'english', level: 'L3', word: 'region', pron: '리전',
    cue: '리(里)장님이 다스리는 우리 지역',
    scene: '이장님이 마을 지도를 펼쳐 "여기가 우리 리!" 하는 장면',
    meaning: '지역, 지방',
    example: 'This region is famous for its apples.' },
  { id: 'e-curious', type: 'english', level: 'L3', word: 'curious', pron: '큐리어스',
    cue: '퀴리 부인은 호기심 대장',
    scene: '퀴리 부인이 반짝이는 눈으로 실험을 들여다보는 장면',
    meaning: '호기심 많은, 궁금한',
    example: 'The curious cat opened the box.' },
  { id: 'e-effort', type: 'english', level: 'L3', word: 'effort', pron: '에퍼트',
    cue: '요새(fort)를 쌓으려면 돌 하나하나의 노력',
    scene: '돌을 하나씩 쌓아 튼튼한 요새를 만드는 장면',
    meaning: '노력, 수고',
    example: 'Success needs time and effort.' },

  /* ── 고유어 15 ────────────────────────────── */
  { id: 'n-ganeum', type: 'native', level: 'L3', word: '가늠하다',
    scene: '활을 쏘기 전, 한쪽 눈을 감고 과녁까지의 거리를 눈으로 재는 장면',
    syn: ['짐작하다', '어림하다'],
    meaning: '겉으로 보고 형편이나 정도를 대강 짐작하다',
    example: '하늘빛을 보고 비가 올지 가늠해 보았다.' },
  { id: 'n-hearida', type: 'native', level: 'L3', word: '헤아리다',
    scene: '밤하늘의 별을 하나, 둘 세다가 친구의 마음까지 짚어 보는 장면',
    syn: ['살피다', '짐작하다'],
    meaning: '수를 세다, 남의 마음이나 형편을 짚어 생각하다',
    example: '엄마는 말하지 않아도 내 마음을 헤아려 주셨다.' },
  { id: 'n-doesaegida', type: 'native', level: 'L3', word: '되새기다',
    scene: '소가 삼킨 풀을 다시 꺼내 씹듯, 들은 말을 다시 꺼내 곱씹는 장면',
    syn: ['곱씹다', '반추하다'],
    meaning: '지난 일이나 말을 다시 떠올려 곰곰이 생각하다',
    example: '선생님의 말씀을 잠들기 전에 되새겼다.' },
  { id: 'n-aureuda', type: 'native', level: 'L3', word: '아우르다',
    scene: '두 팔을 크게 벌려 흩어진 친구들을 한 품에 모으는 장면',
    syn: ['모으다', '포괄하다'],
    meaning: '여럿을 한데 모아 어울리게 하다',
    example: '반장은 반 전체를 아우르는 리더였다.' },
  { id: 'n-mureupsseuda', type: 'native', level: 'L4', word: '무릅쓰다',
    scene: '쏟아지는 비를 머리부터 뒤집어쓰고도 앞으로 걸어가는 장면',
    syn: ['감수하다', '견디다'],
    meaning: '어려움을 알면서도 그대로 견디며 해내다',
    example: '위험을 무릅쓰고 물에 빠진 강아지를 구했다.' },
  { id: 'n-galmuri', type: 'native', level: 'L3', word: '갈무리',
    scene: '가을에 거둔 곡식을 광에 차곡차곡 쟁여 넣는 장면',
    syn: ['정리', '마무리'],
    meaning: '물건을 잘 정리해 간수함, 일을 잘 마무리함',
    example: '오늘 배운 내용을 공책에 갈무리했다.' },
  { id: 'n-gomgomi', type: 'native', level: 'L3', word: '곰곰이',
    scene: '곰이 굴 속에서 팔짱을 끼고 오래오래 생각하는 장면',
    syn: ['깊이', '차분히'],
    meaning: '여러모로 깊이 생각하는 모양',
    example: '곰곰이 생각해 보니 내 잘못도 있었다.' },
  { id: 'n-seoseumda', type: 'native', level: 'L3', word: '서슴다',
    scene: '문고리를 잡고 들어갈까 말까 멈칫거리는 장면',
    syn: ['머뭇거리다', '주저하다'],
    meaning: '결단을 내리지 못하고 머뭇거리다',
    example: '그는 서슴지 않고 번쩍 손을 들었다.' },
  { id: 'n-eorimjapda', type: 'native', level: 'L3', word: '어림잡다',
    scene: '쌀가마니를 들어 보지도 않고 눈대중으로 "한 20킬로?" 하는 장면',
    syn: ['가늠하다', '어림하다'],
    meaning: '대강 짐작으로 헤아리다',
    example: '관중 수를 어림잡아 천 명으로 보았다.' },
  { id: 'n-dadogida', type: 'native', level: 'L2', word: '다독이다',
    scene: '우는 동생의 등을 토닥토닥 두드려 주는 장면',
    syn: ['달래다', '위로하다'],
    meaning: '가볍게 두드리며 달래고 감싸다',
    example: '실수한 친구를 다독여 주었다.' },
  { id: 'n-samuchida', type: 'native', level: 'L4', word: '사무치다',
    scene: '겨울바람이 뼛속까지 파고들듯, 그리움이 마음 깊이 파고드는 장면',
    syn: ['저미다', '깊이 스미다'],
    meaning: '깊이 스며들어 마음속까지 미치다',
    example: '고향 생각이 뼈에 사무쳤다.' },
  { id: 'n-eokcheok', type: 'native', level: 'L4', word: '억척스럽다',
    scene: '새벽 시장에서 무거운 리어카를 끌고도 씩씩한 할머니의 손',
    syn: ['악착같다', '끈질기다'],
    meaning: '어려움에도 굽히지 않고 몹시 모질고 끈덕지다',
    example: '어머니는 억척스럽게 우리 남매를 키우셨다.' },
  { id: 'n-onggolchada', type: 'native', level: 'L4', word: '옹골차다',
    scene: '알이 빈틈없이 꽉 들어찬 옥수수',
    syn: ['야무지다', '알차다'],
    meaning: '속이 꽉 차서 실속이 있다',
    example: '몸집은 작아도 옹골찬 선수다.' },
  { id: 'n-galpi', type: 'native', level: 'L3', word: '갈피',
    scene: '두꺼운 책 사이에 끼운 책갈피 — 지금 어디쯤인지 알려 준다',
    syn: ['두서', '가닥'],
    meaning: '일이나 마음의 갈래와 방향',
    example: '갑작스러운 소식에 갈피를 잡지 못했다.' },
  { id: 'n-nwiuchida', type: 'native', level: 'L3', word: '뉘우치다',
    scene: '일기장 앞에서 고개를 숙이고 "내가 잘못했구나" 하는 장면',
    syn: ['반성하다', '후회하다'],
    meaning: '잘못을 깨닫고 스스로 꾸짖다',
    example: '거짓말한 것을 깊이 뉘우쳤다.' },

  /* ── 한자어 추가 30 (비문학·학업 어휘) ────── */
  { id: 'h-gwanchal', type: 'hanja', level: 'L2', word: '관찰', hanja: '觀察',
    parts: [{ ch: '觀', hun: '볼', eum: '관' }, { ch: '察', hun: '살필', eum: '찰' }],
    literal: '보고 살핀다',
    meaning: '사물이나 현상을 주의 깊게 살펴봄',
    example: '개미의 움직임을 며칠 동안 관찰했다.' },
  { id: 'h-gwanjeom2', type: 'hanja', level: 'L3', word: '직관', hanja: '直觀',
    parts: [{ ch: '直', hun: '곧을', eum: '직' }, { ch: '觀', hun: '볼', eum: '관' }],
    literal: '곧바로 본다',
    meaning: '따져 보지 않고 대번에 알아차리는 것',
    example: '수학 문제를 직관으로 풀면 실수하기 쉽다.' },
  { id: 'h-chugjeong', type: 'hanja', level: 'L2', word: '측정', hanja: '測定',
    parts: [{ ch: '測', hun: '잴', eum: '측' }, { ch: '定', hun: '정할', eum: '정' }],
    literal: '재어서 정한다',
    meaning: '길이·무게 등을 재어서 값을 정함',
    example: '실험 전에 물의 온도를 측정했다.' },
  { id: 'h-yeonron', type: 'hanja', level: 'L4', word: '연역', hanja: '演繹',
    parts: [{ ch: '演', hun: '펼', eum: '연' }, { ch: '繹', hun: '풀어낼', eum: '역' }],
    literal: '펼쳐서 풀어낸다',
    meaning: '일반 원리에서 개별 사실을 이끌어 내는 추론',
    example: '모든 사람은 죽는다에서 시작하는 연역 추론.' },
  { id: 'h-gwinap', type: 'hanja', level: 'L4', word: '귀납', hanja: '歸納',
    parts: [{ ch: '歸', hun: '돌아갈', eum: '귀' }, { ch: '納', hun: '들일', eum: '납' }],
    literal: '모아서 들인다',
    meaning: '여러 사례를 모아 일반 법칙을 이끌어 냄',
    example: '관찰 결과를 모아 귀납으로 결론을 세웠다.' },
  { id: 'h-geungeo', type: 'hanja', level: 'L3', word: '근거', hanja: '根據',
    parts: [{ ch: '根', hun: '뿌리', eum: '근' }, { ch: '據', hun: '의거할', eum: '거' }],
    literal: '뿌리로 삼아 의지한다',
    meaning: '주장이 기대고 있는 바탕이나 이유',
    example: '주장에는 반드시 근거가 따라야 한다.' },
  { id: 'h-jeungmyeong', type: 'hanja', level: 'L3', word: '증명', hanja: '證明',
    parts: [{ ch: '證', hun: '증거', eum: '증' }, { ch: '明', hun: '밝을', eum: '명' }],
    literal: '증거로 밝힌다',
    meaning: '사실이나 결론이 참임을 밝히는 일',
    example: '피타고라스 정리를 그림으로 증명했다.' },
  { id: 'h-banbak', type: 'hanja', level: 'L4', word: '반박', hanja: '反駁',
    parts: [{ ch: '反', hun: '돌이킬', eum: '반' }, { ch: '駁', hun: '논박할', eum: '박' }],
    literal: '되받아 논박한다',
    meaning: '남의 의견에 반대하여 잘못을 지적함',
    example: '상대의 근거가 약하다며 조목조목 반박했다.' },
  { id: 'h-jeonhwan', type: 'hanja', level: 'L3', word: '전환', hanja: '轉換',
    parts: [{ ch: '轉', hun: '구를', eum: '전' }, { ch: '換', hun: '바꿀', eum: '환' }],
    literal: '굴려서 바꾼다',
    meaning: '방향이나 상태를 다른 것으로 바꿈',
    example: '분위기 전환을 위해 잠시 쉬었다.' },
  { id: 'h-yeonghyang', type: 'hanja', level: 'L2', word: '영향', hanja: '影響',
    parts: [{ ch: '影', hun: '그림자', eum: '영' }, { ch: '響', hun: '울릴', eum: '향' }],
    literal: '그림자처럼 따라오고 메아리처럼 울린다',
    meaning: '어떤 것이 다른 것에 미치는 작용',
    example: '기후 변화는 농사에 큰 영향을 준다.' },
  { id: 'h-hwangyeong', type: 'hanja', level: 'L2', word: '환경', hanja: '環境',
    parts: [{ ch: '環', hun: '고리', eum: '환' }, { ch: '境', hun: '지경', eum: '경' }],
    literal: '둘러싼 경계',
    meaning: '생물을 둘러싸고 영향을 주는 조건',
    example: '깨끗한 환경에서 자란 나무가 튼튼하다.' },
  { id: 'h-jaewon', type: 'hanja', level: 'L2', word: '자원', hanja: '資源',
    parts: [{ ch: '資', hun: '재물', eum: '자' }, { ch: '源', hun: '근원', eum: '원' }],
    literal: '재물의 근원',
    meaning: '생산에 쓰이는 물자나 힘의 원천',
    example: '물은 아껴 써야 할 소중한 자원이다.' },
  { id: 'h-sunhwan', type: 'hanja', level: 'L2', word: '순환', hanja: '循環',
    parts: [{ ch: '循', hun: '돌', eum: '순' }, { ch: '環', hun: '고리', eum: '환' }],
    literal: '고리를 따라 돈다',
    meaning: '주기적으로 돌아 제자리로 오는 일',
    example: '물은 증발과 비로 순환한다.' },
  { id: 'h-gyunhyeong', type: 'hanja', level: 'L2', word: '균형', hanja: '均衡',
    parts: [{ ch: '均', hun: '고를', eum: '균' }, { ch: '衡', hun: '저울대', eum: '형' }],
    literal: '저울이 고르다',
    meaning: '어느 쪽으로도 기울지 않고 고른 상태',
    example: '공부와 운동의 균형을 지켰다.' },
  { id: 'h-galdeung', type: 'hanja', level: 'L2', word: '갈등', hanja: '葛藤',
    parts: [{ ch: '葛', hun: '칡', eum: '갈' }, { ch: '藤', hun: '등나무', eum: '등' }],
    literal: '칡과 등나무가 서로 얽힘',
    meaning: '서로 부딪쳐 얽힌 어려운 상태',
    example: '두 인물의 갈등이 이야기를 이끈다.' },
  { id: 'h-hyeopryeok', type: 'hanja', level: 'L2', word: '협력', hanja: '協力',
    parts: [{ ch: '協', hun: '화합할', eum: '협' }, { ch: '力', hun: '힘', eum: '력' }],
    literal: '힘을 합한다',
    meaning: '힘을 모아 서로 도움',
    example: '모둠원들의 협력으로 과제를 마쳤다.' },
  { id: 'h-chaegim', type: 'hanja', level: 'L2', word: '책임', hanja: '責任',
    parts: [{ ch: '責', hun: '꾸짖을', eum: '책' }, { ch: '任', hun: '맡길', eum: '임' }],
    literal: '맡은 일을 꾸짖어 묻는다',
    meaning: '맡아서 해야 할 임무나 그에 따른 부담',
    example: '자기가 한 말에는 책임이 따른다.' },
  { id: 'h-gwonri', type: 'hanja', level: 'L2', word: '권리', hanja: '權利',
    parts: [{ ch: '權', hun: '권세', eum: '권' }, { ch: '利', hun: '이로울', eum: '리' }],
    literal: '누릴 수 있는 힘과 이익',
    meaning: '당연히 누리거나 주장할 수 있는 자격',
    example: '모든 학생은 배울 권리가 있다.' },
  { id: 'h-uimu', type: 'hanja', level: 'L2', word: '의무', hanja: '義務',
    parts: [{ ch: '義', hun: '옳을', eum: '의' }, { ch: '務', hun: '힘쓸', eum: '무' }],
    literal: '옳은 일에 힘쓴다',
    meaning: '마땅히 해야 할 일',
    example: '권리에는 의무가 함께 따른다.' },
  { id: 'h-jedo', type: 'hanja', level: 'L3', word: '제도', hanja: '制度',
    parts: [{ ch: '制', hun: '마를', eum: '제' }, { ch: '度', hun: '법도', eum: '도' }],
    literal: '마름질해 정한 법도',
    meaning: '사회가 함께 지키기로 정한 규칙과 틀',
    example: '학교 급식은 오래된 제도다.' },
  { id: 'h-hyeonsang', type: 'hanja', level: 'L3', word: '현상', hanja: '現象',
    parts: [{ ch: '現', hun: '나타날', eum: '현' }, { ch: '象', hun: '모양', eum: '상' }],
    literal: '나타난 모양',
    meaning: '눈에 보이거나 관찰되는 사물의 모습',
    example: '무지개는 빛이 꺾여 생기는 현상이다.' },
  { id: 'h-bonjil', type: 'hanja', level: 'L3', word: '본질', hanja: '本質',
    parts: [{ ch: '本', hun: '근본', eum: '본' }, { ch: '質', hun: '바탕', eum: '질' }],
    literal: '근본이 되는 바탕',
    meaning: '그것을 그것답게 만드는 가장 중요한 성질',
    example: '겉모습보다 본질을 봐야 한다.' },
  { id: 'h-gaenyeom', type: 'hanja', level: 'L3', word: '개념', hanja: '槪念',
    parts: [{ ch: '槪', hun: '대개', eum: '개' }, { ch: '念', hun: '생각', eum: '념' }],
    literal: '대체로 잡은 생각',
    meaning: '여러 대상에서 공통된 것을 뽑아 만든 생각',
    example: '먼저 개념을 정확히 잡아야 문제가 풀린다.' },
  { id: 'h-bunryu', type: 'hanja', level: 'L2', word: '분류', hanja: '分類',
    parts: [{ ch: '分', hun: '나눌', eum: '분' }, { ch: '類', hun: '무리', eum: '류' }],
    literal: '무리로 나눈다',
    meaning: '공통점에 따라 갈래를 지어 나눔',
    example: '도서관 책은 주제별로 분류되어 있다.' },
  { id: 'h-bigyo', type: 'hanja', level: 'L2', word: '비교', hanja: '比較',
    parts: [{ ch: '比', hun: '견줄', eum: '비' }, { ch: '較', hun: '견줄', eum: '교' }],
    literal: '견주고 또 견준다',
    meaning: '둘 이상을 맞대어 공통점과 차이를 살핌',
    example: '두 실험 결과를 비교해 보았다.' },
  { id: 'h-yoyak', type: 'hanja', level: 'L2', word: '요약', hanja: '要約',
    parts: [{ ch: '要', hun: '요긴할', eum: '요' }, { ch: '約', hun: '묶을', eum: '약' }],
    literal: '요긴한 것만 묶는다',
    meaning: '중요한 것만 골라 짧게 간추림',
    example: '읽은 글을 세 문장으로 요약했다.' },
  { id: 'h-siljeung', type: 'hanja', level: 'L3', word: '실증', hanja: '實證',
    parts: [{ ch: '實', hun: '열매', eum: '실' }, { ch: '證', hun: '증거', eum: '증' }],
    literal: '실제 증거로 보인다',
    meaning: '실제 사실이나 실험으로 증명함',
    example: '가설을 실험으로 실증했다.' },
  { id: 'h-gaseol', type: 'hanja', level: 'L3', word: '가설', hanja: '假說',
    parts: [{ ch: '假', hun: '거짓', eum: '가' }, { ch: '說', hun: '말씀', eum: '설' }],
    literal: '임시로 세운 말',
    meaning: '검증하기 전에 임시로 세운 설명',
    example: '가설을 세우고 실험으로 확인한다.' },
  { id: 'h-oryu', type: 'hanja', level: 'L3', word: '오류', hanja: '誤謬',
    parts: [{ ch: '誤', hun: '그르칠', eum: '오' }, { ch: '謬', hun: '그릇될', eum: '류' }],
    literal: '그르치고 그릇되다',
    meaning: '생각이나 계산이 잘못된 것',
    example: '계산 과정에 작은 오류가 있었다.' },
  { id: 'h-boan', type: 'hanja', level: 'L3', word: '보완', hanja: '補完',
    parts: [{ ch: '補', hun: '기울', eum: '보' }, { ch: '完', hun: '완전할', eum: '완' }],
    literal: '기워서 완전하게 한다',
    meaning: '모자란 것을 채워 온전하게 함',
    example: '부족한 부분을 자료로 보완했다.' },

  /* ── 고유어 추가 30 ──────────────────────── */
  { id: 'n-buchugida', type: 'native', level: 'L2', word: '부추기다',
    scene: '옆에서 등을 툭툭 밀며 "해 봐, 해 봐" 하는 장면',
    syn: ['꼬드기다', '충동질하다'],
    meaning: '남을 들쑤셔 어떤 일을 하게 만들다',
    example: '친구가 부추겨서 무대에 올라갔다.' },
  { id: 'n-tteoreomida', type: 'native', level: 'L2', word: '떠올리다',
    scene: '물에 잠긴 공이 수면 위로 떠오르듯 기억이 쑥 올라오는 장면',
    syn: ['상기하다', '생각해 내다'],
    meaning: '기억을 되살려 생각해 내다',
    example: '어제 배운 단어를 떠올려 보았다.' },
  { id: 'n-jitgutda', type: 'native', level: 'L2', word: '짓궂다',
    scene: '몰래 의자를 빼놓고 킥킥 웃는 장난꾸러기',
    syn: ['짓궂다', '얄궂다'],
    meaning: '남을 곤란하게 할 만큼 장난이 심하다',
    example: '짓궂은 농담에 friends가 웃음을 터뜨렸다.' },
  { id: 'n-eosaekhada', type: 'native', level: 'L2', word: '어색하다',
    scene: '처음 만난 사람과 엘리베이터에 단둘이 서 있는 순간',
    syn: ['서먹하다', '부자연스럽다'],
    meaning: '자연스럽지 못하고 서먹하다',
    example: '첫 인사는 늘 조금 어색하다.' },
  { id: 'n-neuggeutada', type: 'native', level: 'L2', word: '느긋하다',
    scene: '해먹에 누워 다리를 흔들며 구름을 보는 오후',
    syn: ['여유롭다', '태평하다'],
    meaning: '서두르지 않고 마음이 넉넉하다',
    example: '시험이 끝나 느긋한 주말을 보냈다.' },
  { id: 'n-jogeupada', type: 'native', level: 'L2', word: '조급하다',
    scene: '신호가 안 바뀌는데 발을 동동 구르는 모습',
    syn: ['성급하다', '초조하다'],
    meaning: '참을성 없이 몹시 급하다',
    example: '조급하게 굴다가 답을 잘못 썼다.' },
  { id: 'n-kkomkkomhada', type: 'native', level: 'L2', word: '꼼꼼하다',
    scene: '자로 잰 듯 줄을 맞춰 필기하는 공책',
    syn: ['세심하다', '빈틈없다'],
    meaning: '빈틈없이 자세하고 차분하다',
    example: '꼼꼼하게 검토했더니 실수가 없었다.' },
  { id: 'n-heosulhada', type: 'native', level: 'L2', word: '허술하다',
    scene: '못이 빠져 삐걱거리는 낡은 울타리',
    syn: ['엉성하다', '부실하다'],
    meaning: '치밀하지 못해 빈틈이 있다',
    example: '계획이 허술해서 중간에 막혔다.' },
  { id: 'n-tteotteothada', type: 'native', level: 'L3', word: '떳떳하다',
    scene: '고개를 들고 어깨를 편 채 걸어 나오는 뒷모습',
    syn: ['당당하다', '거리낌 없다'],
    meaning: '숨길 것이 없어 마음이 당당하다',
    example: '정직하게 했으니 떳떳하다.' },
  { id: 'n-mimanghada', type: 'native', level: 'L3', word: '미덥다',
    scene: '무거운 짐을 말없이 들어 주는 든든한 어깨',
    syn: ['믿음직하다', '든든하다'],
    meaning: '믿을 만하다',
    example: '맡겨 두면 미더운 친구다.' },
  { id: 'n-sseulmoitda', type: 'native', level: 'L3', word: '쓸모없다',
    scene: '고장 나서 서랍 구석에 처박힌 낡은 리모컨',
    syn: ['무용하다', '소용없다'],
    meaning: '쓸 만한 가치가 없다',
    example: '버릴 뻔한 물건이 알고 보니 쓸모없지 않았다.' },
  { id: 'n-dodeuraji', type: 'native', level: 'L3', word: '도드라지다',
    scene: '회색 돌 사이에서 혼자 새빨간 단풍잎',
    syn: ['두드러지다', '눈에 띄다'],
    meaning: '겉으로 뚜렷하게 드러나다',
    example: '그림에서 붉은색이 유난히 도드라졌다.' },
  { id: 'n-eoulrida', type: 'native', level: 'L2', word: '어울리다',
    scene: '퍼즐 조각이 딱 맞아 들어가는 순간',
    syn: ['조화되다', '맞아떨어지다'],
    meaning: '서로 잘 맞아 조화를 이루다',
    example: '파란 셔츠가 얼굴색과 잘 어울린다.' },
  { id: 'n-beotida', type: 'native', level: 'L2', word: '버티다',
    scene: '거센 바람에도 뿌리를 박고 서 있는 나무',
    syn: ['견디다', '지탱하다'],
    meaning: '어려움을 참고 견뎌 내다',
    example: '마지막 한 문제까지 버텨서 풀었다.' },
  { id: 'n-mumeotgeorida', type: 'native', level: 'L2', word: '머뭇거리다',
    scene: '손을 들까 말까 하며 팔을 반쯤 올렸다 내리는 모습',
    syn: ['주저하다', '망설이다'],
    meaning: '선뜻 하지 못하고 자꾸 망설이다',
    example: '대답을 못 하고 한참 머뭇거렸다.' },
  { id: 'n-eongkeuda', type: 'native', level: 'L3', word: '엉기다',
    scene: '식은 죽이 한 덩어리로 굳어 숟가락에 붙는 모습',
    syn: ['엉키다', '뭉치다'],
    meaning: '한데 뭉쳐 굳거나 얽히다',
    example: '실이 엉겨서 풀기 어려웠다.' },
  { id: 'n-nunchi', type: 'native', level: 'L2', word: '눈치',
    scene: '말없이 표정만 보고 분위기를 읽어 내는 순간',
    syn: ['기색', '낌새'],
    meaning: '남의 마음이나 분위기를 알아채는 힘',
    example: '눈치가 빨라 먼저 도와주었다.' },
  { id: 'n-mitbatchim', type: 'native', level: 'L2', word: '밑바탕',
    scene: '그림을 그리기 전에 먼저 칠해 두는 흰 바탕',
    syn: ['기초', '토대'],
    meaning: '어떤 것의 근본이 되는 바탕',
    example: '기초 어휘가 독해의 밑바탕이다.' },
  { id: 'n-teumteumi', type: 'native', level: 'L2', word: '틈틈이',
    scene: '벽돌 사이 좁은 틈마다 자라난 작은 풀',
    syn: ['짬짬이', '수시로'],
    meaning: '겨를이 날 때마다 조금씩',
    example: '쉬는 시간마다 틈틈이 단어를 외웠다.' },
  { id: 'n-jureojulmuk', type: 'native', level: 'L2', word: '줄곧',
    scene: '출발선부터 결승선까지 한 번도 안 멈춘 주자',
    syn: ['내내', '계속'],
    meaning: '끊이지 않고 내내',
    example: '아침부터 줄곧 비가 내렸다.' },
  { id: 'n-daedanhi', type: 'native', level: 'L3', word: '대뜸',
    scene: '문을 열자마자 인사도 없이 바로 본론을 꺼내는 사람',
    syn: ['다짜고짜', '단박에'],
    meaning: '앞뒤 없이 그 자리에서 바로',
    example: '들어오자마자 대뜸 이유를 물었다.' },
  { id: 'n-gyeoulhada', type: 'native', level: 'L2', word: '겨루다',
    scene: '팔씨름으로 팽팽하게 맞선 두 팔',
    syn: ['다투다', '경쟁하다'],
    meaning: '서로 이기려고 힘이나 실력을 다투다',
    example: '두 팀이 결승에서 겨루었다.' },
  { id: 'n-doedolabuda', type: 'native', level: 'L2', word: '되돌아보다',
    scene: '언덕 위에서 걸어온 길을 뒤돌아보는 뒷모습',
    syn: ['회고하다', '돌이키다'],
    meaning: '지난 일을 다시 생각해 보다',
    example: '한 학기를 되돌아보며 계획을 세웠다.' },
  { id: 'n-ttokbaro', type: 'native', level: 'L2', word: '똑바로',
    scene: '자를 대고 그은 것처럼 곧게 뻗은 선',
    syn: ['곧게', '바르게'],
    meaning: '비뚤어지지 않고 곧게',
    example: '허리를 똑바로 펴고 앉았다.' },
  { id: 'n-eoseolpeuda', type: 'native', level: 'L3', word: '어설프다',
    scene: '처음 잡아 본 젓가락이 자꾸 미끄러지는 손',
    syn: ['서투르다', '엉성하다'],
    meaning: '익숙하지 못해 서투르다',
    example: '어설픈 솜씨였지만 끝까지 만들었다.' },
  { id: 'n-nunbusida', type: 'native', level: 'L2', word: '눈부시다',
    scene: '한겨울 눈밭에 햇빛이 쏟아져 눈을 못 뜨는 순간',
    syn: ['찬란하다', '빛나다'],
    meaning: '빛이 강해 바로 보기 어렵다, 매우 훌륭하다',
    example: '올해 그 선수의 활약은 눈부셨다.' },
  { id: 'n-seolpeuda', type: 'native', level: 'L3', word: '섣부르다',
    scene: '반죽이 덜 익었는데 뚜껑을 열어 버린 냄비',
    syn: ['성급하다', '어설프다'],
    meaning: '설익어서 조심성 없이 급하다',
    example: '섣부른 판단은 실수를 부른다.' },
  { id: 'n-gadeukhada', type: 'native', level: 'L2', word: '가득하다',
    scene: '물이 찰랑찰랑 넘치기 직전인 컵',
    syn: ['꽉 차다', '충만하다'],
    meaning: '빈 곳 없이 꽉 차 있다',
    example: '교실이 웃음소리로 가득했다.' },
  { id: 'n-mitgeurojida', type: 'native', level: 'L2', word: '미끄러지다',
    scene: '얼음판에 발을 딛자마자 쭉 밀려나는 발',
    syn: ['빗나가다', '밀리다'],
    meaning: '미끄러워 밀려 나가다, 시험에 떨어지다',
    example: '빙판에서 미끄러질 뻔했다.' },
  { id: 'n-chagunchagun', type: 'native', level: 'L2', word: '차근차근',
    scene: '계단을 한 칸씩 또박또박 밟아 올라가는 발걸음',
    syn: ['하나하나', '천천히'],
    meaning: '서두르지 않고 순서대로 조리 있게',
    example: '차근차근 설명하니 모두 이해했다.' },

  /* ── 영어 추가 30 ────────────────────────── */
  { id: 'e-analyze', type: 'english', level: 'L3', word: 'analyze', pron: '애널라이즈',
    cue: '"애? 널 라이즈(쪼개)!" 잘게 쪼개 살핀다',
    scene: '레고를 조각조각 분해해 놓고 들여다보는 장면',
    meaning: '분석하다',
    example: 'Let’s analyze the data together.' },
  { id: 'e-describe', type: 'english', level: 'L3', word: 'describe', pron: '디스크라이브',
    cue: 'scribe(쓰다) — 아래로 죽 써 내려가며 설명',
    scene: '본 것을 공책에 줄줄 받아 적는 기자',
    root: { stem: 'scrib', sense: '쓰다', family: ['script', 'subscribe'] },
    meaning: '묘사하다, 설명하다',
    example: 'Describe what you saw in the picture.' },
  { id: 'e-explain', type: 'english', level: 'L3', word: 'explain', pron: '익스플레인',
    cue: 'ex(밖) + plain(평평) — 밖으로 평평하게 펴서 보여 준다',
    scene: '구겨진 지도를 쫙 펴서 길을 짚어 주는 장면',
    meaning: '설명하다',
    example: 'Can you explain this rule again?' },
  { id: 'e-suggest', type: 'english', level: 'L3', word: 'suggest', pron: '서제스트',
    cue: '"서서 제스처로" 이렇게 해 보라고 권한다',
    scene: '손짓으로 다른 길을 가리키며 권하는 모습',
    meaning: '제안하다',
    example: 'I suggest we start with the easy part.' },
  { id: 'e-require', type: 'english', level: 'L3', word: 'require', pron: '리콰이어',
    cue: 're(다시) + quire(구하다) — 꼭 있어야 해서 거듭 구한다',
    scene: '입장하려는데 "표가 꼭 필요합니다" 하고 막는 직원',
    meaning: '필요로 하다, 요구하다',
    example: 'This job requires patience.' },
  { id: 'e-provide', type: 'english', level: 'L3', word: 'provide', pron: '프로바이드',
    cue: 'pro(앞) + vid(보다) — 미리 내다보고 챙겨 준다',
    scene: '소풍 전날 도시락을 미리 싸 두는 부모님',
    root: { stem: 'vid', sense: '보다', family: ['video', 'evidence'] },
    meaning: '제공하다',
    example: 'The school provides free lunch.' },
  { id: 'e-improve', type: 'english', level: 'L3', word: 'improve', pron: '임프루브',
    cue: '"임(in) + prove" — 안으로 더 좋아짐을 증명한다',
    scene: '성적 그래프가 한 칸씩 위로 올라가는 장면',
    meaning: '개선하다, 나아지다',
    example: 'Reading every day improves your vocabulary.' },
  { id: 'e-reduce', type: 'english', level: 'L3', word: 'reduce', pron: '리듀스',
    cue: 're(뒤) + duce(이끌다) — 뒤로 끌어 줄인다',
    scene: '풍선에서 바람을 빼 작아지게 하는 장면',
    root: { stem: 'duc', sense: '이끌다', family: ['produce', 'introduce'] },
    meaning: '줄이다',
    example: 'We should reduce plastic waste.' },
  { id: 'e-increase', type: 'english', level: 'L3', word: 'increase', pron: '인크리스',
    cue: '"인(in) + 크리(크게)" — 안에서 크게 불어난다',
    scene: '작은 눈덩이가 굴러가며 점점 커지는 장면',
    meaning: '증가하다, 늘리다',
    example: 'The number of readers increased sharply.' },
  { id: 'e-affect', type: 'english', level: 'L3', word: 'affect', pron: '어펙트',
    cue: 'af(향해) + fect(만들다) — 다가가 변화를 만든다',
    scene: '돌 하나가 물에 떨어져 파문이 번지는 장면',
    root: { stem: 'fect', sense: '만들다', family: ['effect', 'perfect'] },
    meaning: '영향을 미치다',
    example: 'Sleep affects how well you remember.' },
  { id: 'e-cause', type: 'english', level: 'L3', word: 'cause', pron: '코즈',
    cue: '"코즈(때문에)" — 그것 때문에 벌어진다',
    scene: '도미노 첫 조각이 쓰러지자 줄줄이 넘어지는 장면',
    meaning: '원인, 일으키다',
    example: 'Heavy rain caused the delay.' },
  { id: 'e-result', type: 'english', level: 'L3', word: 'result', pron: '리절트',
    cue: 're(다시) + sult(뛰다) — 튀어나온 결과',
    scene: '실험이 끝나고 화면에 숫자가 탁 튀어나오는 장면',
    meaning: '결과, 결과로 생기다',
    example: 'The result surprised everyone.' },
  { id: 'e-observe2', type: 'english', level: 'L3', word: 'measure', pron: '메저',
    cue: '"메(매) + 저(자)" — 자를 매어 잰다',
    scene: '줄자를 팽팽히 당겨 길이를 재는 손',
    meaning: '측정하다, 치수',
    example: 'Measure the length before you cut.' },
  { id: 'e-decide', type: 'english', level: 'L3', word: 'decide', pron: '디사이드',
    cue: 'de(떼어) + cide(자르다) — 잘라서 정한다',
    scene: '갈림길에서 한쪽을 가위로 딱 잘라 내는 장면',
    meaning: '결정하다',
    example: 'We decided to start early.' },
  { id: 'e-consider', type: 'english', level: 'L3', word: 'consider', pron: '컨시더',
    cue: '"큰 시더(생각)" — 크게 두루 생각한다',
    scene: '별자리를 하나하나 짚어 가며 오래 헤아리는 사람',
    meaning: '고려하다, 여기다',
    example: 'Consider both sides before you judge.' },
  { id: 'e-realize', type: 'english', level: 'L4', word: 'realize', pron: '리얼라이즈',
    cue: 'real(진짜) — 진짜였구나 하고 깨닫는다',
    scene: '머리 위에 전구가 반짝 켜지는 순간',
    meaning: '깨닫다, 실현하다',
    example: 'I realized my mistake too late.' },
  { id: 'e-recognize', type: 'english', level: 'L4', word: 'recognize', pron: '레커그나이즈',
    cue: 're(다시) + cogn(알다) — 다시 보고 알아본다',
    scene: '오랜만에 만난 친구 얼굴을 알아보고 손을 드는 장면',
    root: { stem: 'cogn', sense: '알다', family: ['cognitive', 'recognition'] },
    meaning: '알아보다, 인정하다',
    example: 'I didn’t recognize him with short hair.' },
  { id: 'e-remain', type: 'english', level: 'L3', word: 'remain', pron: '리메인',
    cue: 're(계속) + main(남다) — 계속 남아 있다',
    scene: '모두 떠난 교실에 홀로 남은 의자 하나',
    meaning: '남다, 계속 ~이다',
    example: 'Only three cookies remain.' },
  { id: 'e-avoid', type: 'english', level: 'L3', word: 'avoid', pron: '어보이드',
    cue: 'void(빈 곳) — 비워 두고 피한다',
    scene: '웅덩이를 폴짝 뛰어넘어 피해 가는 발',
    meaning: '피하다',
    example: 'Avoid studying right before you sleep.' },
  { id: 'e-achieve2', type: 'english', level: 'L4', word: 'obtain', pron: '옵테인',
    cue: 'ob(향해) + tain(붙잡다) — 향해 가서 붙잡는다',
    scene: '높은 선반의 상자를 까치발로 잡아 내리는 장면',
    root: { stem: 'tain', sense: '붙잡다', family: ['contain', 'maintain'] },
    meaning: '얻다, 획득하다',
    example: 'She obtained a perfect score.' },
  { id: 'e-contain', type: 'english', level: 'L3', word: 'contain', pron: '컨테인',
    cue: 'con(함께) + tain(붙잡다) — 안에 담아 붙들고 있다',
    scene: '컨테이너 안에 짐이 가득 담겨 있는 장면',
    root: { stem: 'tain', sense: '붙잡다', family: ['obtain', 'maintain'] },
    meaning: '포함하다, 담고 있다',
    example: 'This juice contains no sugar.' },
  { id: 'e-appear', type: 'english', level: 'L3', word: 'appear', pron: '어피어',
    cue: '"어? 피어(났다)!" 불쑥 나타난다',
    scene: '땅에서 새싹이 쑥 올라오는 장면',
    meaning: '나타나다, ~처럼 보이다',
    example: 'A rainbow appeared after the rain.' },
  { id: 'e-disappear', type: 'english', level: 'L3', word: 'disappear', pron: '디서피어',
    cue: 'dis(반대) + appear(나타나다) — 반대로 사라진다',
    scene: '마술사가 보를 걷자 상자가 사라진 무대',
    meaning: '사라지다',
    example: 'The stars disappear at sunrise.' },
  { id: 'e-similar', type: 'english', level: 'L3', word: 'similar', pron: '시밀러',
    cue: '"시(같은) + 밀러(거울)" — 거울처럼 닮았다',
    scene: '쌍둥이가 나란히 서서 같은 포즈를 한 장면',
    meaning: '비슷한',
    example: 'Their handwriting looks similar.' },
  { id: 'e-different', type: 'english', level: 'L3', word: 'various', pron: '베리어스',
    cue: 'vary(변하다) — 여러 가지로 변한다',
    scene: '팔레트에 색이 열두 가지 짜여 있는 장면',
    meaning: '다양한',
    example: 'The library has various kinds of books.' },
  { id: 'e-obvious', type: 'english', level: 'L4', word: 'obvious', pron: '아비어스',
    cue: 'ob(앞에) + via(길) — 길 앞에 뻔히 놓여 있다',
    scene: '길 한복판에 커다란 바위가 떡 놓인 장면',
    meaning: '분명한, 뻔한',
    example: 'The answer was obvious to everyone.' },
  { id: 'e-accurate', type: 'english', level: 'L4', word: 'accurate', pron: '애큐릿',
    cue: 'cure(주의) — 주의를 다해 딱 맞힌다',
    scene: '화살이 과녁 한가운데에 정확히 꽂힌 장면',
    meaning: '정확한',
    example: 'His measurement was surprisingly accurate.' },
  { id: 'e-complex', type: 'english', level: 'L4', word: 'complex', pron: '컴플렉스',
    cue: 'com(함께) + plex(엮다) — 여러 겹으로 얽혔다',
    scene: '실이 사방으로 얽혀 풀기 힘든 뭉치',
    meaning: '복잡한',
    example: 'The problem is more complex than it looks.' },
  { id: 'e-familiar', type: 'english', level: 'L3', word: 'familiar', pron: '퍼밀리어',
    cue: 'family(가족) — 가족처럼 익숙하다',
    scene: '매일 지나는 골목이 눈 감고도 그려지는 장면',
    meaning: '익숙한, 낯익은',
    example: 'This song sounds familiar.' },
  { id: 'e-effort2', type: 'english', level: 'L4', word: 'attempt', pron: '어템프트',
    cue: 'temp(시도) — 한 번 해 보려고 손을 뻗는다',
    scene: '높은 봉을 잡으려 몇 번이고 뛰어오르는 모습',
    meaning: '시도하다, 시도',
    example: 'She made three attempts before succeeding.' },

  /* ══════════════════════════════════════════════════════════════════
     L1 (7세~초2) — 36개
     초2 학생이 "영어 단어가 너무 어렵다"고 한 뒤 새로 썼다. 위의 135개는
     전부 중등 이상이라 학년대로 걸러 봐야 초저학년 몫이 0개였다.
     여기 말들은 아이가 이미 입으로는 쓰고 있는데 뜻을 또렷이 모르는 것들이다.
     ══════════════════════════════════════════════════════════════════ */
  /* ── L1 한자어 12 ── */
  { id: 'h1-hakgyo', type: 'hanja', level: 'L1', word: '학교', hanja: '學校',
    parts: [{ ch: '學', hun: '배울', eum: '학' }, { ch: '校', hun: '학교', eum: '교' }],
    literal: '배우는 집',
    meaning: '함께 모여 배우는 곳',
    example: '아침마다 학교에 간다.' },
  { id: 'h1-gyosil', type: 'hanja', level: 'L1', word: '교실', hanja: '敎室',
    parts: [{ ch: '敎', hun: '가르칠', eum: '교' }, { ch: '室', hun: '방', eum: '실' }],
    literal: '가르치는 방',
    meaning: '수업을 하는 방',
    example: '우리 교실은 이 층에 있다.' },
  { id: 'h1-sigan', type: 'hanja', level: 'L1', word: '시간', hanja: '時間',
    parts: [{ ch: '時', hun: '때', eum: '시' }, { ch: '間', hun: '사이', eum: '간' }],
    literal: '때와 때 사이',
    meaning: '어떤 때부터 어떤 때까지의 사이',
    example: '쉬는 시간에 물을 마셨다.' },
  { id: 'h1-jayeon', type: 'hanja', level: 'L1', word: '자연', hanja: '自然',
    parts: [{ ch: '自', hun: '스스로', eum: '자' }, { ch: '然', hun: '그럴', eum: '연' }],
    literal: '스스로 그러함',
    meaning: '사람이 만들지 않고 저절로 있는 것들',
    example: '산과 바다는 자연이 준 선물이다.' },
  { id: 'h1-dongmul', type: 'hanja', level: 'L1', word: '동물', hanja: '動物',
    parts: [{ ch: '動', hun: '움직일', eum: '동' }, { ch: '物', hun: '물건', eum: '물' }],
    literal: '움직이는 것',
    meaning: '스스로 움직이며 사는 생물',
    example: '동물원에서 코끼리를 보았다.' },
  { id: 'h1-sikmul', type: 'hanja', level: 'L1', word: '식물', hanja: '植物',
    parts: [{ ch: '植', hun: '심을', eum: '식' }, { ch: '物', hun: '물건', eum: '물' }],
    literal: '심는 것',
    meaning: '한자리에 뿌리내리고 사는 생물',
    example: '교실에서 식물을 기른다.' },
  { id: 'h1-gajok', type: 'hanja', level: 'L1', word: '가족', hanja: '家族',
    parts: [{ ch: '家', hun: '집', eum: '가' }, { ch: '族', hun: '겨레', eum: '족' }],
    literal: '한 집 사람들',
    meaning: '함께 사는 가까운 사람들',
    example: '주말에 가족과 나들이를 갔다.' },
  { id: 'h1-anjeon', type: 'hanja', level: 'L1', word: '안전', hanja: '安全',
    parts: [{ ch: '安', hun: '편안할', eum: '안' }, { ch: '全', hun: '온전할', eum: '전' }],
    literal: '편안하고 온전함',
    meaning: '다치거나 위험하지 않음',
    example: '길을 건널 때는 안전이 먼저다.' },
  { id: 'h1-yaksok', type: 'hanja', level: 'L1', word: '약속', hanja: '約束',
    parts: [{ ch: '約', hun: '맺을', eum: '약' }, { ch: '束', hun: '묶을', eum: '속' }],
    literal: '맺어서 묶음',
    meaning: '앞으로 어떻게 하기로 서로 정하는 일',
    example: '친구와 한 약속을 지켰다.' },
  { id: 'h1-saenghwal', type: 'hanja', level: 'L1', word: '생활', hanja: '生活',
    parts: [{ ch: '生', hun: '날', eum: '생' }, { ch: '活', hun: '살', eum: '활' }],
    literal: '나서 살아감',
    meaning: '날마다 살아가는 일',
    example: '규칙적인 생활이 몸을 튼튼하게 한다.' },
  { id: 'h1-chingu', type: 'hanja', level: 'L1', word: '친구', hanja: '親舊',
    parts: [{ ch: '親', hun: '친할', eum: '친' }, { ch: '舊', hun: '옛', eum: '구' }],
    literal: '오래 친한 사이',
    meaning: '가깝게 오래 사귄 사람',
    example: '친구와 어깨동무를 하고 걸었다.' },
  { id: 'h1-jeongni', type: 'hanja', level: 'L1', word: '정리', hanja: '整理',
    parts: [{ ch: '整', hun: '가지런할', eum: '정' }, { ch: '理', hun: '다스릴', eum: '리' }],
    literal: '가지런히 다스림',
    meaning: '흩어진 것을 제자리에 놓아 깔끔하게 하는 일',
    example: '놀고 나서 장난감을 정리했다.' },

  /* ── L1 영어 12 ── */
  { id: 'e1-big', type: 'english', level: 'L1', word: 'big', pron: '빅',
    cue: '"빅"— 크게 벌린 입',
    scene: '두 팔을 활짝 벌려 "이만큼 커!" 하고 자랑하는 아이',
    meaning: '큰',
    example: 'That is a big dog.' },
  { id: 'e1-small', type: 'english', level: 'L1', word: 'small', pron: '스몰',
    cue: '"스몰"— 손가락을 오므려 조그맣게',
    scene: '엄지와 검지를 붙여 개미만 한 틈을 만들어 보이는 손',
    meaning: '작은',
    example: 'I have a small pencil.' },
  { id: 'e1-happy', type: 'english', level: 'L1', word: 'happy', pron: '해피',
    cue: '"해피"— 해처럼 환한 얼굴',
    scene: '생일 케이크 앞에서 활짝 웃는 얼굴',
    meaning: '기쁜, 행복한',
    example: 'I am happy today.' },
  { id: 'e1-sad', type: 'english', level: 'L1', word: 'sad', pron: '새드',
    cue: '"새드"— 새가 축 처져 앉아 있다',
    scene: '비 오는 창가에 턱을 괴고 앉은 아이',
    meaning: '슬픈',
    example: 'She looks sad.' },
  { id: 'e1-run', type: 'english', level: 'L1', word: 'run', pron: '런',
    cue: '"런"— 운동장을 한 바퀴',
    scene: '출발 신호에 맞춰 흙먼지를 내며 달려 나가는 아이',
    meaning: '달리다',
    example: 'I can run fast.' },
  { id: 'e1-jump', type: 'english', level: 'L1', word: 'jump', pron: '점프',
    cue: '"점프"— 점을 찍듯 콩 뛰어오른다',
    scene: '줄넘기 줄을 넘으려고 두 발을 모아 뛰는 모습',
    meaning: '뛰어오르다',
    example: 'The frog can jump high.' },
  { id: 'e1-water', type: 'english', level: 'L1', word: 'water', pron: '워터',
    cue: '"워터"— 물이 콸콸',
    scene: '운동을 마치고 물통을 들이켜는 장면',
    meaning: '물',
    example: 'I drink water every morning.' },
  { id: 'e1-friend', type: 'english', level: 'L1', word: 'friend', pron: '프렌드',
    cue: '"프렌드"— 곁에 붙어 다니는 사람',
    scene: '어깨동무를 하고 나란히 걸어가는 두 아이',
    meaning: '친구',
    example: 'He is my best friend.' },
  { id: 'e1-school', type: 'english', level: 'L1', word: 'school', pron: '스쿨',
    cue: '"스쿨"— 종이 울리는 곳',
    scene: '아침 종소리에 맞춰 교문으로 들어가는 아이들',
    meaning: '학교',
    example: 'We go to school by bus.' },
  { id: 'e1-animal', type: 'english', level: 'L1', word: 'animal', pron: '애니멀',
    cue: '"애니멀"— 애니메이션에 나오는 동물들',
    scene: '동물원 우리 앞에서 사자와 눈이 마주친 순간',
    meaning: '동물',
    example: 'A rabbit is a small animal.' },
  { id: 'e1-help', type: 'english', level: 'L1', word: 'help', pron: '헬프',
    cue: '"헬프"— 손을 내밀어 준다',
    scene: '넘어진 친구에게 손을 뻗어 일으켜 주는 장면',
    meaning: '돕다, 도움',
    example: 'Can you help me?' },
  { id: 'e1-look', type: 'english', level: 'L1', word: 'look', pron: '룩',
    cue: '"룩"— 두 개의 o 가 눈알 두 개',
    scene: '손가락으로 하늘을 가리키며 "저기 봐!" 하는 아이',
    meaning: '보다, 쳐다보다',
    example: 'Look at the moon.' },

  /* ── L1 고유어 12 ── */
  { id: 'n1-ppudeut', type: 'native', level: 'L1', word: '뿌듯하다',
    scene: '혼자 힘으로 신발끈을 묶고 가슴을 쭉 편 아이',
    syn: ['흐뭇하다', '자랑스럽다'],
    meaning: '마음이 가득 차서 기쁘다',
    example: '동생을 도와주고 나니 뿌듯했다.' },
  { id: 'n1-seolle', type: 'native', level: 'L1', word: '설레다',
    scene: '소풍 전날 밤, 가방을 싸 놓고 잠이 안 오는 밤',
    syn: ['두근거리다', '들뜨다'],
    meaning: '좋은 일이 기다려져 마음이 두근거리다',
    example: '내일 소풍 생각에 설렜다.' },
  { id: 'n1-yamu', type: 'native', level: 'L1', word: '야무지다',
    scene: '작은 손으로 단추를 하나하나 빈틈없이 채우는 모습',
    syn: ['똑 부러지다', '알차다'],
    meaning: '하는 일이 빈틈없고 똑 부러지다',
    example: '동생은 정리를 야무지게 한다.' },
  { id: 'n1-sangnyang', type: 'native', level: 'L1', word: '상냥하다',
    scene: '길을 묻는 사람에게 웃으며 방향을 알려 주는 모습',
    syn: ['다정하다', '부드럽다'],
    meaning: '말과 얼굴빛이 부드럽고 정답다',
    example: '상냥하게 인사하니 기분이 좋아졌다.' },
  { id: 'n1-seulgi', type: 'native', level: 'L1', word: '슬기롭다',
    scene: '싸우는 두 친구 사이에서 좋은 방법을 찾아내는 아이',
    syn: ['지혜롭다', '현명하다'],
    meaning: '일을 잘 헤아려 옳게 풀어낼 줄 알다',
    example: '슬기롭게 문제를 해결했다.' },
  { id: 'n1-bujireon', type: 'native', level: 'L1', word: '부지런하다',
    scene: '해가 뜨기도 전에 일어나 마당을 쓰는 사람',
    syn: ['성실하다', '꾸준하다'],
    meaning: '게으르지 않고 열심히 움직이다',
    example: '부지런한 사람은 아침이 길다.' },
  { id: 'n1-ssikssik', type: 'native', level: 'L1', word: '씩씩하다',
    scene: '무릎이 까졌는데도 툭툭 털고 다시 뛰어가는 아이',
    syn: ['굳세다', '용감하다'],
    meaning: '힘차고 굳세다',
    example: '주사를 씩씩하게 맞았다.' },
  { id: 'n1-salpyeobo', type: 'native', level: 'L1', word: '살펴보다',
    scene: '길을 건너기 전 왼쪽 오른쪽으로 고개를 돌리는 아이',
    syn: ['둘러보다', '눈여겨보다'],
    meaning: '빠뜨리지 않게 자세히 보다',
    example: '건너기 전에 차가 오는지 살펴보았다.' },
  { id: 'n1-domat', type: 'native', level: 'L1', word: '도맡다',
    scene: '청소 당번이 아픈 날, 혼자 빗자루를 다 드는 아이',
    syn: ['떠맡다', '혼자 맡다'],
    meaning: '어떤 일을 혼자서 다 맡다',
    example: '오늘은 내가 설거지를 도맡았다.' },
  { id: 'n1-akki', type: 'native', level: 'L1', word: '아끼다',
    scene: '몽당연필이 될 때까지 깎아 쓰는 손',
    syn: ['소중히 하다', '절약하다'],
    meaning: '함부로 쓰지 않고 소중하게 여기다',
    example: '물을 아껴 쓰자.' },
  { id: 'n1-datu', type: 'native', level: 'L1', word: '다투다',
    scene: '그네를 서로 먼저 타겠다고 목소리가 커진 두 아이',
    syn: ['싸우다', '겨루다'],
    meaning: '서로 자기가 옳다고 하며 싸우다',
    example: '사소한 일로 다투었다가 곧 화해했다.' },
  { id: 'n1-seotu', type: 'native', level: 'L1', word: '서투르다',
    scene: '처음 잡아 보는 젓가락으로 콩을 자꾸 떨어뜨리는 손',
    syn: ['미숙하다', '어설프다'],
    meaning: '익숙하지 않아 잘하지 못하다',
    example: '아직 자전거가 서툴러서 자꾸 넘어진다.' },

  /* ══════════════════════════════════════════════════════════════════
     L2 (초3~6) — 36개. 교과서에서 처음 만나는 말들.
     ══════════════════════════════════════════════════════════════════ */
  /* ── L2 한자어 12 ── */
  { id: 'h2-gwansim', type: 'hanja', level: 'L2', word: '관심', hanja: '關心',
    parts: [{ ch: '關', hun: '관계할', eum: '관' }, { ch: '心', hun: '마음', eum: '심' }],
    literal: '마음이 걸림',
    meaning: '마음이 끌려 자꾸 눈이 가는 것',
    example: '나는 우주에 관심이 많다.' },
  { id: 'h2-noryeok', type: 'hanja', level: 'L2', word: '노력', hanja: '努力',
    parts: [{ ch: '努', hun: '힘쓸', eum: '노' }, { ch: '力', hun: '힘', eum: '력' }],
    literal: '힘을 씀',
    meaning: '목표를 이루려고 힘을 다하는 일',
    example: '꾸준한 노력이 실력을 만든다.' },
  { id: 'h2-balgyeon', type: 'hanja', level: 'L2', word: '발견', hanja: '發見',
    parts: [{ ch: '發', hun: '필', eum: '발' }, { ch: '見', hun: '볼', eum: '견' }],
    literal: '드러나 보임',
    meaning: '아직 알려지지 않은 것을 찾아내는 일',
    example: '새로운 별을 발견했다.' },
  { id: 'h2-silheom', type: 'hanja', level: 'L2', word: '실험', hanja: '實驗',
    parts: [{ ch: '實', hun: '열매', eum: '실' }, { ch: '驗', hun: '시험', eum: '험' }],
    literal: '실제로 시험함',
    meaning: '생각이 맞는지 직접 해 보며 확인하는 일',
    example: '식물이 빛을 향하는지 실험해 보았다.' },
  { id: 'h2-gwangye', type: 'hanja', level: 'L2', word: '관계', hanja: '關係',
    parts: [{ ch: '關', hun: '관계할', eum: '관' }, { ch: '係', hun: '맬', eum: '계' }],
    literal: '서로 매여 있음',
    meaning: '둘 사이에 서로 걸려 있는 이어짐',
    example: '기온과 아이스크림 판매량은 관계가 있다.' },
  { id: 'h2-bangbeop', type: 'hanja', level: 'L2', word: '방법', hanja: '方法',
    parts: [{ ch: '方', hun: '모', eum: '방' }, { ch: '法', hun: '법', eum: '법' }],
    literal: '가는 방향과 규칙',
    meaning: '어떤 일을 해내는 길이나 순서',
    example: '더 쉬운 방법을 찾아보자.' },
  { id: 'h2-gyeolgwa', type: 'hanja', level: 'L2', word: '결과', hanja: '結果',
    parts: [{ ch: '結', hun: '맺을', eum: '결' }, { ch: '果', hun: '열매', eum: '과' }],
    literal: '맺힌 열매',
    meaning: '어떤 일 끝에 나온 것',
    example: '실험 결과를 표로 정리했다.' },
  { id: 'h2-wonin', type: 'hanja', level: 'L2', word: '원인', hanja: '原因',
    parts: [{ ch: '原', hun: '근원', eum: '원' }, { ch: '因', hun: '인할', eum: '인' }],
    literal: '일이 비롯된 뿌리',
    meaning: '어떤 일이 일어나게 만든 까닭',
    example: '불이 난 원인을 조사했다.' },
  { id: 'h2-teukjing', type: 'hanja', level: 'L2', word: '특징', hanja: '特徵',
    parts: [{ ch: '特', hun: '특별할', eum: '특' }, { ch: '徵', hun: '부를', eum: '징' }],
    literal: '특별히 드러나는 표',
    meaning: '다른 것과 구별되는 남다른 점',
    example: '기린의 특징은 긴 목이다.' },
  { id: 'h2-sangsang', type: 'hanja', level: 'L2', word: '상상', hanja: '想像',
    parts: [{ ch: '想', hun: '생각', eum: '상' }, { ch: '像', hun: '모양', eum: '상' }],
    literal: '생각으로 모양을 그림',
    meaning: '눈앞에 없는 것을 머릿속에 그려 보는 일',
    example: '바다 밑 도시를 상상해 보았다.' },
  { id: 'h2-pyohyeon', type: 'hanja', level: 'L2', word: '표현', hanja: '表現',
    parts: [{ ch: '表', hun: '겉', eum: '표' }, { ch: '現', hun: '나타날', eum: '현' }],
    literal: '겉으로 나타냄',
    meaning: '생각이나 느낌을 말·글·몸짓으로 드러내는 일',
    example: '고마운 마음을 편지로 표현했다.' },
  { id: 'h2-gyehoek', type: 'hanja', level: 'L2', word: '계획', hanja: '計劃',
    parts: [{ ch: '計', hun: '셀', eum: '계' }, { ch: '劃', hun: '그을', eum: '획' }],
    literal: '세어 보고 금을 그음',
    meaning: '앞으로 할 일을 미리 짜 두는 것',
    example: '방학 계획을 세웠다.' },

  /* ── L2 영어 12 ── */
  { id: 'e2-remember', type: 'english', level: 'L2', word: 'remember', pron: '리멤버',
    cue: 're(다시) + member(구성원) — 흩어진 조각을 다시 불러 모은다',
    scene: '앨범을 넘기다 잊고 있던 날이 떠오르는 순간',
    meaning: '기억하다, 떠올리다',
    example: 'I remember her name.' },
  { id: 'e2-forget', type: 'english', level: 'L2', word: 'forget', pron: '포겟',
    cue: 'for(멀리) + get(잡다) — 손에서 놓쳐 멀어진다',
    scene: '우산을 버스에 두고 내린 뒤 빈손을 내려다보는 장면',
    meaning: '잊다, 잊어버리다',
    example: "Don't forget your homework." },
  { id: 'e2-together', type: 'english', level: 'L2', word: 'together', pron: '투게더',
    cue: 'to + gether(gather 모이다) — 하나로 모인다',
    scene: '여럿이 손을 겹쳐 올리고 구호를 외치는 장면',
    meaning: '함께, 같이',
    example: 'We finished the work together.' },
  { id: 'e2-different', type: 'english', level: 'L2', word: 'different', pron: '디퍼런트',
    cue: 'dif(떨어져) + fer(나르다) — 서로 다른 데로 갈린다',
    scene: '똑같아 보이는 두 그림에서 틀린 곳을 찾아내는 놀이',
    meaning: '다른, 서로 같지 않은',
    example: 'These two answers are different.' },
  { id: 'e2-important', type: 'english', level: 'L2', word: 'important', pron: '임포턴트',
    cue: 'im(안으로) + port(항구) — 항구로 들여올 만큼 값진 것',
    scene: '여러 짐 가운데 하나만 골라 가슴에 안는 장면',
    meaning: '중요한, 소중한',
    example: 'Sleep is important for health.' },
  { id: 'e2-question', type: 'english', level: 'L2', word: 'question', pron: '퀘스천',
    cue: 'quest(찾아 나섬) — 답을 찾아 떠나는 것이 질문',
    scene: '손을 번쩍 들고 "왜요?" 하고 묻는 아이',
    meaning: '질문, 물음',
    example: 'May I ask a question?' },
  { id: 'e2-answer', type: 'english', level: 'L2', word: 'answer', pron: '앤서',
    cue: '"앤서"— 안에서 나오는 대답',
    scene: '칠판 앞에서 분필로 답을 또박또박 적는 손',
    meaning: '대답, 답; 대답하다',
    example: 'I know the answer.' },
  { id: 'e2-careful', type: 'english', level: 'L2', word: 'careful', pron: '케어풀',
    cue: 'care(돌봄) + ful(가득) — 마음을 가득 쓴다',
    scene: '가득 찬 물컵을 두 손으로 받쳐 옮기는 걸음',
    meaning: '조심스러운, 주의 깊은',
    example: 'Be careful with the glass.' },
  { id: 'e2-quiet', type: 'english', level: 'L2', word: 'quiet', pron: '콰이엇',
    cue: '"콰이엇"— 쉿, 소리를 끈다',
    scene: '도서관에서 입에 손가락을 대는 사서 선생님',
    meaning: '조용한',
    example: 'The library is very quiet.' },
  { id: 'e2-choose', type: 'english', level: 'L2', word: 'choose', pron: '추즈',
    cue: '"추즈"— 여럿 중에 쭉 뽑아낸다',
    scene: '아이스크림 통 앞에서 한참 고민하다 하나를 가리키는 손가락',
    meaning: '고르다, 선택하다',
    example: 'Choose the best answer.' },
  { id: 'e2-strong', type: 'english', level: 'L2', word: 'strong', pron: '스트롱',
    cue: '"스트롱"— 팔에 힘줄이 툭',
    scene: '무거운 상자를 번쩍 들어 올리는 팔',
    meaning: '강한, 튼튼한',
    example: 'He is strong enough to lift it.' },
  { id: 'e2-weather', type: 'english', level: 'L2', word: 'weather', pron: '웨더',
    cue: '"웨더"— 오늘 하늘은 어떨까',
    scene: '아침에 창문을 열고 하늘을 올려다보는 장면',
    meaning: '날씨',
    example: 'The weather is nice today.' },

  /* ── L2 고유어 12 ── */
  { id: 'n2-aesseu', type: 'native', level: 'L2', word: '애쓰다',
    scene: '무거운 문을 두 손으로 밀며 이마에 힘줄이 서는 모습',
    syn: ['힘쓰다', '노력하다'],
    meaning: '마음과 힘을 다해 무엇을 하려 하다',
    example: '늦지 않으려고 애썼지만 결국 늦었다.' },
  { id: 'n2-salpi', type: 'native', level: 'L2', word: '살피다',
    scene: '교실을 한 바퀴 돌며 빠진 물건이 없는지 훑는 눈',
    syn: ['둘러보다', '헤아리다'],
    meaning: '빠짐없이 두루 자세히 보다',
    example: '친구의 기분을 살피며 말을 골랐다.' },
  { id: 'n2-gyeonju', type: 'native', level: 'L2', word: '견주다',
    scene: '두 자를 나란히 놓고 어느 쪽이 긴지 눈으로 재는 손',
    syn: ['비교하다', '대보다'],
    meaning: '둘을 나란히 놓고 어떤지 대어 보다',
    example: '작년 기록과 견주어 보니 많이 늘었다.' },
  { id: 'n2-bukdodu', type: 'native', level: 'L2', word: '북돋우다',
    scene: '지친 주자의 등을 두드리며 "할 수 있어!" 외치는 친구',
    syn: ['격려하다', '기운을 주다'],
    meaning: '기운이 나도록 곁에서 도와주다',
    example: '선생님의 한마디가 용기를 북돋웠다.' },
  { id: 'n2-ireuda', type: 'native', level: 'L2', word: '이르다',
    scene: '아직 아무도 오지 않은 텅 빈 교실에 혼자 앉아 있는 아침',
    syn: ['빠르다', '앞서다'],
    meaning: '때가 보통보다 앞서다',
    example: '아직 결론을 내리기에는 이르다.' },
  { id: 'n2-samga', type: 'native', level: 'L2', word: '삼가다',
    scene: '하려던 말을 입술 앞에서 도로 삼키는 얼굴',
    syn: ['자제하다', '조심하다'],
    meaning: '조심하여 하지 않거나 덜 하다',
    example: '도서관에서는 큰 소리를 삼가야 한다.' },
  { id: 'n2-duru', type: 'native', level: 'L2', word: '두루',
    scene: '전시장을 구석구석 빠짐없이 돌아보는 발걸음',
    syn: ['골고루', '널리'],
    meaning: '빠짐없이 여기저기 다',
    example: '여러 의견을 두루 들어 보았다.' },
  { id: 'n2-yeotae', type: 'native', level: 'L2', word: '여태',
    scene: '해가 지도록 답장을 기다리며 휴대폰을 들여다보는 밤',
    syn: ['이제까지', '아직'],
    meaning: '지금까지, 아직도',
    example: '여태 한 번도 늦은 적이 없다.' },
  { id: 'n2-dajap', type: 'native', level: 'L2', word: '다잡다',
    scene: '풀린 신발끈을 다시 꽉 묶고 출발선에 서는 모습',
    syn: ['추스르다', '단단히 하다'],
    meaning: '흐트러진 마음이나 자세를 단단히 하다',
    example: '마음을 다잡고 다시 책을 폈다.' },
  { id: 'n2-byeoreu', type: 'native', level: 'L2', word: '벼르다',
    scene: '달력에 동그라미를 쳐 두고 그날만 손꼽아 기다리는 모습',
    syn: ['마음먹다', '기다리다'],
    meaning: '어떤 일을 하려고 마음먹고 기회를 기다리다',
    example: '벼르던 자전거를 드디어 샀다.' },
  { id: 'n2-eogeutna', type: 'native', level: 'L2', word: '어긋나다',
    scene: '맞물려야 할 톱니 두 개가 살짝 비껴 헛도는 장면',
    syn: ['빗나가다', '틀어지다'],
    meaning: '서로 맞지 않고 어그러지다',
    example: '예상과 어긋난 결과가 나왔다.' },
  { id: 'n2-geodeul', type: 'native', level: 'L2', word: '거들다',
    scene: '무거운 상자를 든 사람 곁에서 한쪽 모서리를 함께 잡는 손',
    syn: ['돕다', '보태다'],
    meaning: '남이 하는 일을 옆에서 도와주다',
    example: '설거지를 거들었더니 금방 끝났다.' }

];

if (typeof module !== 'undefined' && module.exports) module.exports = { WB_WORDS };
